      SUBROUTINE RSWZ(NM,N,A,W,Z,B,IERR,KMAX)
C*
C*    COMPUTES THE EIGENVALUES AND EIGENVECTORS
C*    OF A REAL SYMMETRIC MATRIX
C*
C*    NM      - FIRST DIMENSION OF MATRICES A AND Z, THE SAME
C*              VALUE SET ON DECLARATION AT THE CALLING ROUTINE
C*    N       - THE ORDER OF THE EIGEN-PROBLEM (MUST BE .LE. NM)
C*    A(NM,N) - INPUT SYMMETRIC MATRIX (FULL STORAGE)
C*    W(N)    - OUTPUT EIGENVALUES (ORDERED
C*              IN ASCENDENT MAGNITUDE VALUES)
C*    Z(NM,N) - EIGENVECTORS (EACH COLUMN IS ASSOCIATED
C*              TO THE CORRESPONDING EIGENVALUE)
C*    B(N)    - WORKING VECTOR
C*    IERR    - ERROR INDEX:
C*            = 0                  - NORMAL TERMINATION
C*            = 10*N               - N IS GREATER THAN NM
C*            = OTHER VALUE THAN 0 - THE COMPUTATION DOES NOT
C*              CONVERGE AFTER 50 ITERATIONS, BUT IT COMPUTES
C*              THE EIGENVALUES TILL IERR.
C*    KMAX    - NUMBER OF VERTICAL LEVELS
C*
C*    FORMAL ARGUMENTS:
C*
      INTEGER N,NM,IERR,KMAX
      REAL A(NM,N,KMAX),W(N,KMAX),Z(NM,N,KMAX),B(N,KMAX)
      INTEGER LMAX
      PARAMETER (LMAX=11)
      REAL AA(LMAX,LMAX),WW(LMAX),ZZ(LMAX,LMAX),BB(LMAX)
C*
C*    CHECK FOR INPUT ERRORS
C*
      INTEGER I,J,K
C*
      IF (N .GT. NM) THEN
      IERR=10*N
      RETURN
      ENDIF
C*
C*    FIND EIGENVALUES AND EIGENVECTORS
C*
      DO K=1,KMAX
      DO J=1,N
      WW(J)=W(J,K)
      BB(J)=B(J,K)
      DO I=1,NM
      AA(I,J)=A(I,J,K)
      ZZ(I,J)=Z(I,J,K)
      ENDDO
      ENDDO
      CALL TRED2(NM,N,AA,WW,BB,ZZ)
      CALL TQL2(NM,N,WW,BB,ZZ,IERR)
      DO J=1,N
      W(J,K)=WW(J)
      B(J,K)=BB(J)
      DO I=1,NM
      A(I,J,K)=AA(I,J)
      Z(I,J,K)=ZZ(I,J)
      ENDDO
      ENDDO
      ENDDO
C*
      RETURN
      END
