      SUBROUTINE GSCTIJ(IMAX,JMAX,FLON,GLAT,
     *                  FLONW,FLONE,GLATN,GLATS,
     *                  IW,IE,JN,JS)
C*
      INTEGER IMAX,JMAX,IW,IE,JS,JN
      REAL FLONW,FLONE,GLATN,GLATS
      REAL FLON(IMAX),GLAT(JMAX)
C*
      INTEGER I,J
      REAL DXW,DXE,DX,DYN,DYS,DY
C*
      IF (FLONW .LT. 0.0) FLONW=FLONW+360.0
      IF (FLONE .LT. 0.0) FLONE=FLONE+360.0
      DXW=361.0
      DXE=361.0
      DO I=1,IMAX
      DX=ABS(FLONW-FLON(I))
      DXW=MIN(DXW,DX)
      IF (DXW .EQ. DX) IW=I
      DX=ABS(FLONE-FLON(I))
      DXE=MIN(DXE,DX)
      IF (DXE .EQ. DX) IE=I
      ENDDO
      FLONW=FLON(IW)
      FLONE=FLON(IE)
C*
      DYN=181.0
      DYS=181.0
      DO J=1,JMAX
      DY=ABS(GLATN-GLAT(J))
      DYN=MIN(DYN,DY)
      IF (DYN .EQ. DY) JN=J
      DY=ABS(GLATS-GLAT(J))
      DYS=MIN(DYS,DY)
      IF (DYS .EQ. DY) JS=J
      ENDDO
      GLATN=GLAT(JN)
      GLATS=GLAT(JS)
C*
      RETURN
      END
