       !        
       !        Cray Inc. Decompilation
       !        Notice - This output is provided for information only.
       !        
       !        Cray Inc. reserves the right to change the format of this
       !        information at any time and does not guarantee the
       !        readability or accuracy of this information.
       !        
       !        This information may not be compilable and corresponds to
       !        the internal representation of the program during the
       !        optimization phase of the compilation process.
       !        
       !        Source                :  Prec_LrgScl.f90
       !        File                  :  Prec_LrgScl.cg
       !        Network               :  Gemini interconnect
       !        Target                :  X86, 64-bit, sse3
       !        
   36.       
   36.       subroutine initlrgscl
   39.       rlocp = 2508.4610790364322
   41.       rgrav = 1.020408163265306e-1
   42.       rlrv = -5452.7691736782708
   43.       $const_S0 = 6.110000000000001e-1 * _expn( -( -5452.7691736782708 / tbase ) )
   44.       const1 = 6.22e-1 * $const_S0
   45.       const2 = -3.78e-1 * $const_S0
   46.       xx1 = -13678059.245141592
   47.       return
   47.       end
   47.       
   59.       
   59.       subroutine lrgscl( geshem, tf, qs, qf, ps, del, sl, dt, mlrg, latco, ncols, kmax )
   59.       $LCS_ncols_0 = 0[loc( ncols ),0]
   59.       $MR_ncols_11 = $LCS_ncols_0
   59.       t$3 = $MR_ncols_11
   59.       $LCS_kmax_1 = 0[loc( kmax ),0]
   59.       $MR_kmax_12 = $LCS_kmax_1
   59.       t$4 = $MR_kmax_12
   59.       t$18 = int( _alloc( max( 0, $LCS_ncols_0 ) * ( 56 + 24 * max( 0, $LCS_kmax_1 ) ) ), 8 )
  159.       t$19 = t$18
  155.       $LCS_2 = max( 0, $MR_ncols_11 )
  155.       t$22 = t$18 + _lsh( $LCS_2, 4 )
  158.       $LCS_MR_kmax_6 = $MR_kmax_12
  158.       $LCS_4 = max( 0, $LCS_MR_kmax_6 )
  158.       $LCS_3 = _lsh( $LCS_4, 3 )
  158.       t$25 = t$18 + $LCS_2 * ( 16 + $LCS_3 )
  157.       t$28 = t$18 + $LCS_2 * ( 24 + $LCS_3 )
  154.       t$31 = t$18 + $LCS_2 * ( 32 + $LCS_3 )
  160.       t$34 = t$18 + $LCS_2 * ( 48 + $LCS_3 )
  156.       $LCS_5 = _lsh( $LCS_4, 4 )
  156.       t$37 = t$18 + $LCS_2 * ( 48 + $LCS_5 )
  161.       t$40 = t$18 + $LCS_2 * ( 56 + $LCS_5 )
  171.       $dtsqrt_S8 = _sqrt( 0[loc( dt ),0].L )
  173.       if ( $MR_kmax_12 > 0 ) then
  174.          if ( $MR_ncols_11 > 0 ) then
  173.             $I_L173_S247 = 0
  173.             if ( $MR_kmax_12 >= 4 ) then
  173.                $I_L173_S246 = 0
  174.                $LCS_7 = ( 0xfffffffffffffffdUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_6 ) )
  174.                if ( $LCS_7 > $MR_kmax_12 ) then
  174.                   $LB_Y0 = 1
  174.                   $UB_Y1 = $LCS_MR_kmax_6
  174.                   $Subscript_Y2 = 1
  174.                   $Subscript_Y3 = $LCS_7
  174.                   $Subscript_Y4 = 4
  174.                   _rbounds_error( $_File_Y40, $Line_Y42, $_Name_Y41, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y43 )
  174.                   $LB_Y0 = 1
  174.                   $LCS_MR_kmax_8 = $MR_kmax_12
  174.                   $UB_Y1 = $LCS_MR_kmax_8
  174.                   $Subscript_Y2 = 1
  174.                   $Subscript_Y3 = ( 0xfffffffffffffffdUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_8 ) )
  174.                   $Subscript_Y4 = 4
  174.                   _rbounds_error( $_File_Y40, $Line_Y42, $_Name_Y44, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y45 )
  174.                endif
  174.                $LCS_MR_kmax_9 = $MR_kmax_12
  174.                $LCS_10 = ( 0xfffffffffffffffeUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_9 ) )
  174.                if ( $LCS_10 > $MR_kmax_12 ) then
  174.                   $LB_Y0 = 1
  174.                   $UB_Y1 = $LCS_MR_kmax_9
  174.                   $Subscript_Y2 = 2
  174.                   $Subscript_Y3 = $LCS_10
  174.                   $Subscript_Y4 = 4
  174.                   _rbounds_error( $_File_Y40, $Line_Y42, $_Name_Y46, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y47 )
  174.                   $LB_Y0 = 1
  174.                   $LCS_MR_kmax_11 = $MR_kmax_12
  174.                   $UB_Y1 = $LCS_MR_kmax_11
  174.                   $Subscript_Y2 = 2
  174.                   $Subscript_Y3 = ( 0xfffffffffffffffeUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_11 ) )
  174.                   $Subscript_Y4 = 4
  174.                   _rbounds_error( $_File_Y40, $Line_Y42, $_Name_Y48, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y49 )
  174.                endif
  174.                $LCS_MR_kmax_12 = $MR_kmax_12
  174.                $LCS_13 = ( 0xffffffffffffffffUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_12 ) )
  174.                if ( $LCS_13 > $MR_kmax_12 ) then
  174.                   $LB_Y0 = 1
  174.                   $UB_Y1 = $LCS_MR_kmax_12
  174.                   $Subscript_Y2 = 3
  174.                   $Subscript_Y3 = $LCS_13
  174.                   $Subscript_Y4 = 4
  174.                   _rbounds_error( $_File_Y40, $Line_Y42, $_Name_Y50, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y51 )
  174.                   $LB_Y0 = 1
  174.                   $LCS_MR_kmax_14 = $MR_kmax_12
  174.                   $UB_Y1 = $LCS_MR_kmax_14
  174.                   $Subscript_Y2 = 3
  174.                   $Subscript_Y3 = ( 0xffffffffffffffffUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_14 ) )
  174.                   $Subscript_Y4 = 4
  174.                   _rbounds_error( $_File_Y40, $Line_Y42, $_Name_Y52, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y53 )
  174.                endif
  174.                $LCS_MR_kmax_15 = $MR_kmax_12
  174.                $LCS_16 = and( 0xfffffffffffffffcUL, $LCS_MR_kmax_15 )
  174.                if ( $LCS_16 > $MR_kmax_12 ) then
  174.                   $LB_Y0 = 1
  174.                   $UB_Y1 = $LCS_MR_kmax_15
  174.                   $Subscript_Y2 = 4
  174.                   $Subscript_Y3 = $LCS_16
  174.                   $Subscript_Y4 = 4
  174.                   _rbounds_error( $_File_Y40, $Line_Y42, $_Name_Y54, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y55 )
  174.                   $LB_Y0 = 1
  174.                   $LCS_MR_kmax_17 = $MR_kmax_12
  174.                   $UB_Y1 = $LCS_MR_kmax_17
  174.                   $Subscript_Y2 = 4
  174.                   $Subscript_Y3 = ( and( 0xfffffffffffffffcUL, $LCS_MR_kmax_17 ) )
  174.                   $Subscript_Y4 = 4
  174.                   _rbounds_error( $_File_Y40, $Line_Y42, $_Name_Y56, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y57 )
  174.                endif
  175.                $LCS_MR_kmax_18 = $MR_kmax_12
  175.                $LCS_19 = ( 0xfffffffffffffffdUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_18 ) )
  175.                if ( $LCS_19 > $MR_kmax_12 ) then
  175.                   $LB_Y0 = 1
  175.                   $UB_Y1 = $LCS_MR_kmax_18
  175.                   $Subscript_Y2 = 1
  175.                   $Subscript_Y3 = $LCS_19
  175.                   $Subscript_Y4 = 4
  175.                   _rbounds_error( $_File_Y40, $Line_Y59, $_Name_Y58, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y60 )
  175.                   $LB_Y0 = 1
  175.                   $LCS_MR_kmax_20 = $MR_kmax_12
  175.                   $UB_Y1 = $LCS_MR_kmax_20
  175.                   $Subscript_Y2 = 1
  175.                   $Subscript_Y3 = ( 0xfffffffffffffffdUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_20 ) )
  175.                   $Subscript_Y4 = 4
  175.                   _rbounds_error( $_File_Y40, $Line_Y59, $_Name_Y63, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y64 )
  175.                endif
  176.                $LCS_MR_kmax_21 = $MR_kmax_12
  176.                $LCS_22 = ( 0xfffffffffffffffdUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_21 ) )
  176.                if ( $LCS_22 > $MR_kmax_12 ) then
  176.                   $LB_Y0 = 1
  176.                   $UB_Y1 = $LCS_MR_kmax_21
  176.                   $Subscript_Y2 = 1
  176.                   $Subscript_Y3 = $LCS_22
  176.                   $Subscript_Y4 = 4
  176.                   _rbounds_error( $_File_Y40, $Line_Y68, $_Name_Y67, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y69 )
  176.                   $LB_Y0 = 1
  176.                   $LCS_MR_kmax_23 = $MR_kmax_12
  176.                   $UB_Y1 = $LCS_MR_kmax_23
  176.                   $Subscript_Y2 = 1
  176.                   $Subscript_Y3 = ( 0xfffffffffffffffdUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_23 ) )
  176.                   $Subscript_Y4 = 4
  176.                   _rbounds_error( $_File_Y40, $Line_Y68, $_Name_Y72, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y73 )
  176.                endif
  177.                $LCS_MR_kmax_24 = $MR_kmax_12
  177.                $LCS_25 = ( 0xfffffffffffffffdUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_24 ) )
  177.                if ( $LCS_25 > $MR_kmax_12 ) then
  177.                   $LB_Y0 = 1
  177.                   $UB_Y1 = $LCS_MR_kmax_24
  177.                   $Subscript_Y2 = 1
  177.                   $Subscript_Y3 = $LCS_25
  177.                   $Subscript_Y4 = 4
  177.                   _rbounds_error( $_File_Y40, $Line_Y76, $_Name_Y67, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y77 )
  177.                endif
  178.                $LCS_MR_kmax_26 = $MR_kmax_12
  178.                $LCS_27 = ( 0xfffffffffffffffdUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_26 ) )
  178.                if ( $LCS_27 > $MR_kmax_12 ) then
  178.                   $LB_Y0 = 1
  178.                   $UB_Y1 = $LCS_MR_kmax_26
  178.                   $Subscript_Y2 = 1
  178.                   $Subscript_Y3 = $LCS_27
  178.                   $Subscript_Y4 = 4
  178.                   _rbounds_error( $_File_Y40, $Line_Y80, $_Name_Y82, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y83 )
  178.                endif
  179.                $LCS_MR_kmax_28 = $MR_kmax_12
  179.                $LCS_29 = ( 0xfffffffffffffffdUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_28 ) )
  179.                if ( $LCS_29 > $MR_kmax_12 ) then
  179.                   $LB_Y0 = 1
  179.                   $UB_Y1 = $LCS_MR_kmax_28
  179.                   $Subscript_Y2 = 1
  179.                   $Subscript_Y3 = $LCS_29
  179.                   $Subscript_Y4 = 4
  179.                   _rbounds_error( $_File_Y40, $Line_Y86, $_Name_Y88, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y89 )
  179.                endif
  175.                $LCS_MR_kmax_30 = $MR_kmax_12
  175.                $LCS_31 = ( 0xfffffffffffffffeUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_30 ) )
  175.                if ( $LCS_31 > $MR_kmax_12 ) then
  175.                   $LB_Y0 = 1
  175.                   $UB_Y1 = $LCS_MR_kmax_30
  175.                   $Subscript_Y2 = 2
  175.                   $Subscript_Y3 = $LCS_31
  175.                   $Subscript_Y4 = 4
  175.                   _rbounds_error( $_File_Y40, $Line_Y93, $_Name_Y92, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y94 )
  175.                   $LB_Y0 = 1
  175.                   $LCS_MR_kmax_32 = $MR_kmax_12
  175.                   $UB_Y1 = $LCS_MR_kmax_32
  175.                   $Subscript_Y2 = 2
  175.                   $Subscript_Y3 = ( 0xfffffffffffffffeUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_32 ) )
  175.                   $Subscript_Y4 = 4
  175.                   _rbounds_error( $_File_Y40, $Line_Y93, $_Name_Y97, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y98 )
  175.                endif
  176.                $LCS_MR_kmax_33 = $MR_kmax_12
  176.                $LCS_34 = ( 0xfffffffffffffffeUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_33 ) )
  176.                if ( $LCS_34 > $MR_kmax_12 ) then
  176.                   $LB_Y0 = 1
  176.                   $UB_Y1 = $LCS_MR_kmax_33
  176.                   $Subscript_Y2 = 2
  176.                   $Subscript_Y3 = $LCS_34
  176.                   $Subscript_Y4 = 4
  176.                   _rbounds_error( $_File_Y40, $Line_Y102, $_Name_Y101, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y103 )
  176.                   $LB_Y0 = 1
  176.                   $LCS_MR_kmax_35 = $MR_kmax_12
  176.                   $UB_Y1 = $LCS_MR_kmax_35
  176.                   $Subscript_Y2 = 2
  176.                   $Subscript_Y3 = ( 0xfffffffffffffffeUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_35 ) )
  176.                   $Subscript_Y4 = 4
  176.                   _rbounds_error( $_File_Y40, $Line_Y102, $_Name_Y106, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y107 )
  176.                endif
  177.                $LCS_MR_kmax_36 = $MR_kmax_12
  177.                $LCS_37 = ( 0xfffffffffffffffeUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_36 ) )
  177.                if ( $LCS_37 > $MR_kmax_12 ) then
  177.                   $LB_Y0 = 1
  177.                   $UB_Y1 = $LCS_MR_kmax_36
  177.                   $Subscript_Y2 = 2
  177.                   $Subscript_Y3 = $LCS_37
  177.                   $Subscript_Y4 = 4
  177.                   _rbounds_error( $_File_Y40, $Line_Y110, $_Name_Y101, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y111 )
  177.                endif
  178.                $LCS_MR_kmax_38 = $MR_kmax_12
  178.                $LCS_39 = ( 0xfffffffffffffffeUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_38 ) )
  178.                if ( $LCS_39 > $MR_kmax_12 ) then
  178.                   $LB_Y0 = 1
  178.                   $UB_Y1 = $LCS_MR_kmax_38
  178.                   $Subscript_Y2 = 2
  178.                   $Subscript_Y3 = $LCS_39
  178.                   $Subscript_Y4 = 4
  178.                   _rbounds_error( $_File_Y40, $Line_Y113, $_Name_Y115, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y116 )
  178.                endif
  179.                $LCS_MR_kmax_40 = $MR_kmax_12
  179.                $LCS_41 = ( 0xfffffffffffffffeUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_40 ) )
  179.                if ( $LCS_41 > $MR_kmax_12 ) then
  179.                   $LB_Y0 = 1
  179.                   $UB_Y1 = $LCS_MR_kmax_40
  179.                   $Subscript_Y2 = 2
  179.                   $Subscript_Y3 = $LCS_41
  179.                   $Subscript_Y4 = 4
  179.                   _rbounds_error( $_File_Y40, $Line_Y119, $_Name_Y121, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y122 )
  179.                endif
  175.                $LCS_MR_kmax_42 = $MR_kmax_12
  175.                $LCS_43 = ( 0xffffffffffffffffUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_42 ) )
  175.                if ( $LCS_43 > $MR_kmax_12 ) then
  175.                   $LB_Y0 = 1
  175.                   $UB_Y1 = $LCS_MR_kmax_42
  175.                   $Subscript_Y2 = 3
  175.                   $Subscript_Y3 = $LCS_43
  175.                   $Subscript_Y4 = 4
  175.                   _rbounds_error( $_File_Y40, $Line_Y126, $_Name_Y125, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y127 )
  175.                   $LB_Y0 = 1
  175.                   $LCS_MR_kmax_44 = $MR_kmax_12
  175.                   $UB_Y1 = $LCS_MR_kmax_44
  175.                   $Subscript_Y2 = 3
  175.                   $Subscript_Y3 = ( 0xffffffffffffffffUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_44 ) )
  175.                   $Subscript_Y4 = 4
  175.                   _rbounds_error( $_File_Y40, $Line_Y126, $_Name_Y130, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y131 )
  175.                endif
  176.                $LCS_MR_kmax_45 = $MR_kmax_12
  176.                $LCS_46 = ( 0xffffffffffffffffUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_45 ) )
  176.                if ( $LCS_46 > $MR_kmax_12 ) then
  176.                   $LB_Y0 = 1
  176.                   $UB_Y1 = $LCS_MR_kmax_45
  176.                   $Subscript_Y2 = 3
  176.                   $Subscript_Y3 = $LCS_46
  176.                   $Subscript_Y4 = 4
  176.                   _rbounds_error( $_File_Y40, $Line_Y135, $_Name_Y134, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y136 )
  176.                   $LB_Y0 = 1
  176.                   $LCS_MR_kmax_47 = $MR_kmax_12
  176.                   $UB_Y1 = $LCS_MR_kmax_47
  176.                   $Subscript_Y2 = 3
  176.                   $Subscript_Y3 = ( 0xffffffffffffffffUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_47 ) )
  176.                   $Subscript_Y4 = 4
  176.                   _rbounds_error( $_File_Y40, $Line_Y135, $_Name_Y139, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y140 )
  176.                endif
  177.                $LCS_MR_kmax_48 = $MR_kmax_12
  177.                $LCS_49 = ( 0xffffffffffffffffUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_48 ) )
  177.                if ( $LCS_49 > $MR_kmax_12 ) then
  177.                   $LB_Y0 = 1
  177.                   $UB_Y1 = $LCS_MR_kmax_48
  177.                   $Subscript_Y2 = 3
  177.                   $Subscript_Y3 = $LCS_49
  177.                   $Subscript_Y4 = 4
  177.                   _rbounds_error( $_File_Y40, $Line_Y143, $_Name_Y134, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y144 )
  177.                endif
  178.                $LCS_MR_kmax_50 = $MR_kmax_12
  178.                $LCS_51 = ( 0xffffffffffffffffUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_50 ) )
  178.                if ( $LCS_51 > $MR_kmax_12 ) then
  178.                   $LB_Y0 = 1
  178.                   $UB_Y1 = $LCS_MR_kmax_50
  178.                   $Subscript_Y2 = 3
  178.                   $Subscript_Y3 = $LCS_51
  178.                   $Subscript_Y4 = 4
  178.                   _rbounds_error( $_File_Y40, $Line_Y146, $_Name_Y148, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y149 )
  178.                endif
  179.                $LCS_MR_kmax_52 = $MR_kmax_12
  179.                $LCS_53 = ( 0xffffffffffffffffUL + and( 0xfffffffffffffffcUL, $LCS_MR_kmax_52 ) )
  179.                if ( $LCS_53 > $MR_kmax_12 ) then
  179.                   $LB_Y0 = 1
  179.                   $UB_Y1 = $LCS_MR_kmax_52
  179.                   $Subscript_Y2 = 3
  179.                   $Subscript_Y3 = $LCS_53
  179.                   $Subscript_Y4 = 4
  179.                   _rbounds_error( $_File_Y40, $Line_Y152, $_Name_Y154, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y155 )
  179.                endif
  175.                $LCS_MR_kmax_54 = $MR_kmax_12
  175.                $LCS_55 = and( 0xfffffffffffffffcUL, $LCS_MR_kmax_54 )
  175.                if ( $LCS_55 > $MR_kmax_12 ) then
  175.                   $LB_Y0 = 1
  175.                   $UB_Y1 = $LCS_MR_kmax_54
  175.                   $Subscript_Y2 = 4
  175.                   $Subscript_Y3 = $LCS_55
  175.                   $Subscript_Y4 = 4
  175.                   _rbounds_error( $_File_Y40, $Line_Y159, $_Name_Y158, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y160 )
  175.                   $LB_Y0 = 1
  175.                   $LCS_MR_kmax_56 = $MR_kmax_12
  175.                   $UB_Y1 = $LCS_MR_kmax_56
  175.                   $Subscript_Y2 = 4
  175.                   $Subscript_Y3 = ( and( 0xfffffffffffffffcUL, $LCS_MR_kmax_56 ) )
  175.                   $Subscript_Y4 = 4
  175.                   _rbounds_error( $_File_Y40, $Line_Y159, $_Name_Y163, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y164 )
  175.                endif
  176.                $LCS_MR_kmax_57 = $MR_kmax_12
  176.                $LCS_58 = and( 0xfffffffffffffffcUL, $LCS_MR_kmax_57 )
  176.                if ( $LCS_58 > $MR_kmax_12 ) then
  176.                   $LB_Y0 = 1
  176.                   $UB_Y1 = $LCS_MR_kmax_57
  176.                   $Subscript_Y2 = 4
  176.                   $Subscript_Y3 = $LCS_58
  176.                   $Subscript_Y4 = 4
  176.                   _rbounds_error( $_File_Y40, $Line_Y168, $_Name_Y167, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y169 )
  176.                   $LB_Y0 = 1
  176.                   $LCS_MR_kmax_59 = $MR_kmax_12
  176.                   $UB_Y1 = $LCS_MR_kmax_59
  176.                   $Subscript_Y2 = 4
  176.                   $Subscript_Y3 = ( and( 0xfffffffffffffffcUL, $LCS_MR_kmax_59 ) )
  176.                   $Subscript_Y4 = 4
  176.                   _rbounds_error( $_File_Y40, $Line_Y168, $_Name_Y172, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y173 )
  176.                endif
  177.                $LCS_MR_kmax_60 = $MR_kmax_12
  177.                $LCS_61 = and( 0xfffffffffffffffcUL, $LCS_MR_kmax_60 )
  177.                if ( $LCS_61 > $MR_kmax_12 ) then
  177.                   $LB_Y0 = 1
  177.                   $UB_Y1 = $LCS_MR_kmax_60
  177.                   $Subscript_Y2 = 4
  177.                   $Subscript_Y3 = $LCS_61
  177.                   $Subscript_Y4 = 4
  177.                   _rbounds_error( $_File_Y40, $Line_Y176, $_Name_Y167, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y177 )
  177.                endif
  178.                $LCS_MR_kmax_62 = $MR_kmax_12
  178.                $LCS_63 = and( 0xfffffffffffffffcUL, $LCS_MR_kmax_62 )
  178.                if ( $LCS_63 > $MR_kmax_12 ) then
  178.                   $LB_Y0 = 1
  178.                   $UB_Y1 = $LCS_MR_kmax_62
  178.                   $Subscript_Y2 = 4
  178.                   $Subscript_Y3 = $LCS_63
  178.                   $Subscript_Y4 = 4
  178.                   _rbounds_error( $_File_Y40, $Line_Y179, $_Name_Y181, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y182 )
  178.                endif
  179.                $LCS_MR_kmax_64 = $MR_kmax_12
  179.                $LCS_65 = and( 0xfffffffffffffffcUL, $LCS_MR_kmax_64 )
  179.                if ( $LCS_65 > $MR_kmax_12 ) then
  179.                   $LB_Y0 = 1
  179.                   $UB_Y1 = $LCS_MR_kmax_64
  179.                   $Subscript_Y2 = 4
  179.                   $Subscript_Y3 = $LCS_65
  179.                   $Subscript_Y4 = 4
  179.                   _rbounds_error( $_File_Y40, $Line_Y185, $_Name_Y187, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y2, $Subscript_Y3, $Subscript_Y4, $Err_count_Y188 )
  179.                endif
  179.                $rgrav_S222 = rgrav
  178.                $const2_S219 = const2
  178.                $const1_S220 = const1
  177.                $rlrv_S218 = rlrv
  175.                $LCS_67 = $MR_ncols_11
  175.                $SR_S245 = 3 * $LCS_67
  175.                $LCS_MR_ncols_66 = $MR_ncols_11
  175.                $SR_S244 = _lsh( $LCS_MR_ncols_66, 1 )
  175.                $SR_S243 = $LCS_MR_ncols_66
  175.                $SR_S242 = 0
  179.                $LCS_24_68 = 24 * $LCS_67
  179.                $SR_S239 = t$22 + $LCS_24_68
  176.                $SR_S238 = t$40 + $LCS_24_68
  175.                $SR_S223 = $LCS_24_68
  175.                $SR_S237 = t$34 + $LCS_24_68
  179.                $LCS_69 = _lsh( $LCS_MR_ncols_66, 4 )
  179.                $SR_S236 = t$22 + $LCS_69
  176.                $SR_S235 = t$40 + $LCS_69
  175.                $SR_S224 = $LCS_69
  175.                $SR_S234 = t$34 + $LCS_69
  179.                $LCS_70 = _lsh( $LCS_MR_ncols_66, 3 )
  179.                $SR_S233 = t$22 + $LCS_70
  176.                $SR_S232 = t$40 + $LCS_70
  175.                $SR_S225 = $LCS_70
  175.                $SR_S231 = t$34 + $LCS_70
  179.                $SR_S230 = t$22
  176.                $SR_S229 = t$40
  175.                $SR_S226 = 0
  175.                $SR_S228 = t$34
  174.                $SR_S221 = 0
  179.                $LIS_E46 = _lsh( $LCS_MR_ncols_66, 5 )
  175.                $LIS_E45 = _lsh( $LCS_MR_ncols_66, 2 )
  181.                $LIS_E44 = _rsh( $MR_kmax_12, 2 )
  178.                $LIS_S19 = loc( qs )
  178.                $LIS_S34 = loc( ps )
  176.                $LIS_S21 = loc( tf )
  175.                $LIS_S22 = loc( qf )
  174.                $LIS_S17 = and( -2, $LCS_67 )
  174.                $LIS_S16 = loc( del )
  174.                $LIS_S14 = loc( sl )
  177.                $LIS_111[0:2:1].L = _bcst( $rlrv_S218, 2 )
  178.                $LIS_110[0:2:1].L = _bcst( $const2_S219, 2 )
  178.                $LIS_109[0:2:1].L = _bcst( $const1_S220, 2 )
  174.                $LIS_E108 = -$LIS_S17
  173. !dir$ blocking_size( 0, 0 )
  173.                do
  174.                   $SCA_sl#1_U0 = 0[$LIS_S14,$SR_S221].L
  174.                   $SCA_del#1_U4 = 0[$LIS_S16,$SR_S221].L
  174.                   $SCA_sl#2_U1 = 1[$LIS_S14,$SR_S221].L
  174.                   $SCA_del#2_U5 = 1[$LIS_S16,$SR_S221].L
  174.                   $SCA_sl#3_U2 = 2[$LIS_S14,$SR_S221].L
  174.                   $SCA_del#3_U6 = 2[$LIS_S16,$SR_S221].L
  174.                   $SCA_sl#4_U3 = 3[$LIS_S14,$SR_S221].L
  174.                   $SCA_del#4_U7 = 3[$LIS_S16,$SR_S221].L
  174.                   $I_L174_S241 = 0
  174.                   if ( $MR_ncols_11 >= 2 ) then !  99.50%
  174.                      $LC_S240 = $LIS_E108
  174.                      $SI_S227 = 0
  179.                      $LIS_83[0:2:1].L = _bcst( $SCA_del#4_U7 * $rgrav_S222, 2 )
  178.                      $LIS_E82 = $LIS_S19 + $SR_S223
  178.                      $LIS_81[0:2:1].L = _bcst( $SCA_sl#4_U3, 2 )
  176.                      $LIS_E80 = $LIS_S21 + $SR_S223
  175.                      $LIS_E79 = $LIS_S22 + $SR_S223
  179.                      $LIS_78[0:2:1].L = _bcst( $SCA_del#3_U6 * $rgrav_S222, 2 )
  178.                      $LIS_E77 = $LIS_S19 + $SR_S224
  178.                      $LIS_76[0:2:1].L = _bcst( $SCA_sl#3_U2, 2 )
  176.                      $LIS_E75 = $LIS_S21 + $SR_S224
  175.                      $LIS_E74 = $LIS_S22 + $SR_S224
  179.                      $LIS_73[0:2:1].L = _bcst( $SCA_del#2_U5 * $rgrav_S222, 2 )
  178.                      $LIS_E72 = $LIS_S19 + $SR_S225
  178.                      $LIS_71[0:2:1].L = _bcst( $SCA_sl#2_U1, 2 )
  176.                      $LIS_E70 = $LIS_S21 + $SR_S225
  175.                      $LIS_E69 = $LIS_S22 + $SR_S225
  179.                      $LIS_68[0:2:1].L = _bcst( $SCA_del#1_U4 * $rgrav_S222, 2 )
  178.                      $LIS_E67 = $LIS_S19 + $SR_S226
  178.                      $LIS_64[0:2:1].L = _bcst( $SCA_sl#1_U0, 2 )
  176.                      $LIS_E62 = $LIS_S21 + $SR_S226
  175.                      $LIS_E61 = $LIS_S22 + $SR_S226
  174.                      if ( $LIS_E108 < -7 ) then
  174. !dir$ blocking_size( 0, 0 )
  174.                         do
  175.                            0[$SI_S227 + $SR_S228:2:1].L = 0[$LIS_E61 + $SI_S227:2:1].L
  176.                            $LCS_tf_71[0:2:1].L = 0[$LIS_E62 + $SI_S227:2:1].L
  176.                            0[$SI_S227 + $SR_S229:2:1].L = $LCS_tf_71[0:2:1].L
  177.                            $V_qs_WR0_S33[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_71[0:2:1].L )
  178.                            $LCS_ps_72[0:2:1].L = 0[$LIS_S34 + $SI_S227:2:1].L
  178.                            $V_qs_WR0_S35[0:2:1].L = ( $V_qs_WR0_S33[0:2:1].L / ( $LCS_ps_72[0:2:1].L * $LIS_64[0:2:1].L + $V_qs_WR0_S33[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            0[$LIS_E67 + $SI_S227:2:1].L = $V_qs_WR0_S35[0:2:1].L
  179.                            0[$SI_S227 + $SR_S230:2:1].L = $LCS_ps_72[0:2:1].L * $LIS_68[0:2:1].L
  175.                            0[$SI_S227 + $SR_S231:2:1].L = 0[$LIS_E69 + $SI_S227:2:1].L
  176.                            $LCS_tf_73[0:2:1].L = 0[$LIS_E70 + $SI_S227:2:1].L
  176.                            0[$SI_S227 + $SR_S232:2:1].L = $LCS_tf_73[0:2:1].L
  177.                            $V_qs_WR0_S39[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_73[0:2:1].L )
  178.                            $V_qs_WR0_S40[0:2:1].L = ( $V_qs_WR0_S39[0:2:1].L / ( $LCS_ps_72[0:2:1].L * $LIS_71[0:2:1].L + $V_qs_WR0_S39[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            0[$LIS_E72 + $SI_S227:2:1].L = $V_qs_WR0_S40[0:2:1].L
  179.                            0[$SI_S227 + $SR_S233:2:1].L = $LCS_ps_72[0:2:1].L * $LIS_73[0:2:1].L
  175.                            0[$SI_S227 + $SR_S234:2:1].L = 0[$LIS_E74 + $SI_S227:2:1].L
  176.                            $LCS_tf_74[0:2:1].L = 0[$LIS_E75 + $SI_S227:2:1].L
  176.                            0[$SI_S227 + $SR_S235:2:1].L = $LCS_tf_74[0:2:1].L
  177.                            $V_qs_WR0_S44[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_74[0:2:1].L )
  178.                            $V_qs_WR0_S45[0:2:1].L = ( $V_qs_WR0_S44[0:2:1].L / ( $LCS_ps_72[0:2:1].L * $LIS_76[0:2:1].L + $V_qs_WR0_S44[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            0[$LIS_E77 + $SI_S227:2:1].L = $V_qs_WR0_S45[0:2:1].L
  179.                            0[$SI_S227 + $SR_S236:2:1].L = $LCS_ps_72[0:2:1].L * $LIS_78[0:2:1].L
  175.                            0[$SI_S227 + $SR_S237:2:1].L = 0[$LIS_E79 + $SI_S227:2:1].L
  176.                            $LCS_tf_75[0:2:1].L = 0[$LIS_E80 + $SI_S227:2:1].L
  176.                            0[$SI_S227 + $SR_S238:2:1].L = $LCS_tf_75[0:2:1].L
  177.                            $V_qs_WR0_S49[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_75[0:2:1].L )
  178.                            $V_qs_WR0_S50[0:2:1].L = ( $V_qs_WR0_S49[0:2:1].L / ( $LCS_ps_72[0:2:1].L * $LIS_81[0:2:1].L + $V_qs_WR0_S49[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            0[$LIS_E82 + $SI_S227:2:1].L = $V_qs_WR0_S50[0:2:1].L
  179.                            0[$SI_S227 + $SR_S239:2:1].L = $LCS_ps_72[0:2:1].L * $LIS_83[0:2:1].L
  175.                            2[$SI_S227 + $SR_S228:2:1].L = 2[$LIS_E61 + $SI_S227:2:1].L
  176.                            $LCS_tf_76[0:2:1].L = 2[$LIS_E62 + $SI_S227:2:1].L
  176.                            2[$SI_S227 + $SR_S229:2:1].L = $LCS_tf_76[0:2:1].L
  177.                            $V_qs_WR0_S52[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_76[0:2:1].L )
  178.                            $LCS_ps_77[0:2:1].L = 2[$LIS_S34 + $SI_S227:2:1].L
  178.                            $V_qs_WR0_S53[0:2:1].L = ( $V_qs_WR0_S52[0:2:1].L / ( $LCS_ps_77[0:2:1].L * $LIS_64[0:2:1].L + $V_qs_WR0_S52[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            2[$LIS_E67 + $SI_S227:2:1].L = $V_qs_WR0_S53[0:2:1].L
  179.                            2[$SI_S227 + $SR_S230:2:1].L = $LCS_ps_77[0:2:1].L * $LIS_68[0:2:1].L
  175.                            2[$SI_S227 + $SR_S231:2:1].L = 2[$LIS_E69 + $SI_S227:2:1].L
  176.                            $LCS_tf_78[0:2:1].L = 2[$LIS_E70 + $SI_S227:2:1].L
  176.                            2[$SI_S227 + $SR_S232:2:1].L = $LCS_tf_78[0:2:1].L
  177.                            $V_qs_WR0_S54[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_78[0:2:1].L )
  178.                            $V_qs_WR0_S55[0:2:1].L = ( $V_qs_WR0_S54[0:2:1].L / ( $LCS_ps_77[0:2:1].L * $LIS_71[0:2:1].L + $V_qs_WR0_S54[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            2[$LIS_E72 + $SI_S227:2:1].L = $V_qs_WR0_S55[0:2:1].L
  179.                            2[$SI_S227 + $SR_S233:2:1].L = $LCS_ps_77[0:2:1].L * $LIS_73[0:2:1].L
  175.                            2[$SI_S227 + $SR_S234:2:1].L = 2[$LIS_E74 + $SI_S227:2:1].L
  176.                            $LCS_tf_79[0:2:1].L = 2[$LIS_E75 + $SI_S227:2:1].L
  176.                            2[$SI_S227 + $SR_S235:2:1].L = $LCS_tf_79[0:2:1].L
  177.                            $V_qs_WR0_S56[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_79[0:2:1].L )
  178.                            $V_qs_WR0_S57[0:2:1].L = ( $V_qs_WR0_S56[0:2:1].L / ( $LCS_ps_77[0:2:1].L * $LIS_76[0:2:1].L + $V_qs_WR0_S56[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            2[$LIS_E77 + $SI_S227:2:1].L = $V_qs_WR0_S57[0:2:1].L
  179.                            2[$SI_S227 + $SR_S236:2:1].L = $LCS_ps_77[0:2:1].L * $LIS_78[0:2:1].L
  175.                            2[$SI_S227 + $SR_S237:2:1].L = 2[$LIS_E79 + $SI_S227:2:1].L
  176.                            $LCS_tf_80[0:2:1].L = 2[$LIS_E80 + $SI_S227:2:1].L
  176.                            2[$SI_S227 + $SR_S238:2:1].L = $LCS_tf_80[0:2:1].L
  177.                            $V_qs_WR0_S58[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_80[0:2:1].L )
  178.                            $V_qs_WR0_S59[0:2:1].L = ( $V_qs_WR0_S58[0:2:1].L / ( $LCS_ps_77[0:2:1].L * $LIS_81[0:2:1].L + $V_qs_WR0_S58[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            2[$LIS_E82 + $SI_S227:2:1].L = $V_qs_WR0_S59[0:2:1].L
  179.                            2[$SI_S227 + $SR_S239:2:1].L = $LCS_ps_77[0:2:1].L * $LIS_83[0:2:1].L
  175.                            4[$SI_S227 + $SR_S228:2:1].L = 4[$LIS_E61 + $SI_S227:2:1].L
  176.                            $LCS_tf_81[0:2:1].L = 4[$LIS_E62 + $SI_S227:2:1].L
  176.                            4[$SI_S227 + $SR_S229:2:1].L = $LCS_tf_81[0:2:1].L
  177.                            $V_qs_WR0_S60[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_81[0:2:1].L )
  178.                            $LCS_ps_82[0:2:1].L = 4[$LIS_S34 + $SI_S227:2:1].L
  178.                            $V_qs_WR0_S61[0:2:1].L = ( $V_qs_WR0_S60[0:2:1].L / ( $LCS_ps_82[0:2:1].L * $LIS_64[0:2:1].L + $V_qs_WR0_S60[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            4[$LIS_E67 + $SI_S227:2:1].L = $V_qs_WR0_S61[0:2:1].L
  179.                            4[$SI_S227 + $SR_S230:2:1].L = $LCS_ps_82[0:2:1].L * $LIS_68[0:2:1].L
  175.                            4[$SI_S227 + $SR_S231:2:1].L = 4[$LIS_E69 + $SI_S227:2:1].L
  176.                            $LCS_tf_83[0:2:1].L = 4[$LIS_E70 + $SI_S227:2:1].L
  176.                            4[$SI_S227 + $SR_S232:2:1].L = $LCS_tf_83[0:2:1].L
  177.                            $V_qs_WR0_S62[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_83[0:2:1].L )
  178.                            $V_qs_WR0_S63[0:2:1].L = ( $V_qs_WR0_S62[0:2:1].L / ( $LCS_ps_82[0:2:1].L * $LIS_71[0:2:1].L + $V_qs_WR0_S62[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            4[$LIS_E72 + $SI_S227:2:1].L = $V_qs_WR0_S63[0:2:1].L
  179.                            4[$SI_S227 + $SR_S233:2:1].L = $LCS_ps_82[0:2:1].L * $LIS_73[0:2:1].L
  175.                            4[$SI_S227 + $SR_S234:2:1].L = 4[$LIS_E74 + $SI_S227:2:1].L
  176.                            $LCS_tf_84[0:2:1].L = 4[$LIS_E75 + $SI_S227:2:1].L
  176.                            4[$SI_S227 + $SR_S235:2:1].L = $LCS_tf_84[0:2:1].L
  177.                            $V_qs_WR0_S64[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_84[0:2:1].L )
  178.                            $V_qs_WR0_S65[0:2:1].L = ( $V_qs_WR0_S64[0:2:1].L / ( $LCS_ps_82[0:2:1].L * $LIS_76[0:2:1].L + $V_qs_WR0_S64[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            4[$LIS_E77 + $SI_S227:2:1].L = $V_qs_WR0_S65[0:2:1].L
  179.                            4[$SI_S227 + $SR_S236:2:1].L = $LCS_ps_82[0:2:1].L * $LIS_78[0:2:1].L
  175.                            4[$SI_S227 + $SR_S237:2:1].L = 4[$LIS_E79 + $SI_S227:2:1].L
  176.                            $LCS_tf_85[0:2:1].L = 4[$LIS_E80 + $SI_S227:2:1].L
  176.                            4[$SI_S227 + $SR_S238:2:1].L = $LCS_tf_85[0:2:1].L
  177.                            $V_qs_WR0_S66[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_85[0:2:1].L )
  178.                            $V_qs_WR0_S67[0:2:1].L = ( $V_qs_WR0_S66[0:2:1].L / ( $LCS_ps_82[0:2:1].L * $LIS_81[0:2:1].L + $V_qs_WR0_S66[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            4[$LIS_E82 + $SI_S227:2:1].L = $V_qs_WR0_S67[0:2:1].L
  179.                            4[$SI_S227 + $SR_S239:2:1].L = $LCS_ps_82[0:2:1].L * $LIS_83[0:2:1].L
  175.                            6[$SI_S227 + $SR_S228:2:1].L = 6[$LIS_E61 + $SI_S227:2:1].L
  176.                            $LCS_tf_86[0:2:1].L = 6[$LIS_E62 + $SI_S227:2:1].L
  176.                            6[$SI_S227 + $SR_S229:2:1].L = $LCS_tf_86[0:2:1].L
  177.                            $V_qs_WR0_S68[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_86[0:2:1].L )
  178.                            $LCS_ps_87[0:2:1].L = 6[$LIS_S34 + $SI_S227:2:1].L
  178.                            $V_qs_WR0_S69[0:2:1].L = ( $V_qs_WR0_S68[0:2:1].L / ( $LCS_ps_87[0:2:1].L * $LIS_64[0:2:1].L + $V_qs_WR0_S68[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            6[$LIS_E67 + $SI_S227:2:1].L = $V_qs_WR0_S69[0:2:1].L
  179.                            6[$SI_S227 + $SR_S230:2:1].L = $LCS_ps_87[0:2:1].L * $LIS_68[0:2:1].L
  175.                            6[$SI_S227 + $SR_S231:2:1].L = 6[$LIS_E69 + $SI_S227:2:1].L
  176.                            $LCS_tf_88[0:2:1].L = 6[$LIS_E70 + $SI_S227:2:1].L
  176.                            6[$SI_S227 + $SR_S232:2:1].L = $LCS_tf_88[0:2:1].L
  177.                            $V_qs_WR0_S70[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_88[0:2:1].L )
  178.                            $V_qs_WR0_S71[0:2:1].L = ( $V_qs_WR0_S70[0:2:1].L / ( $LCS_ps_87[0:2:1].L * $LIS_71[0:2:1].L + $V_qs_WR0_S70[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            6[$LIS_E72 + $SI_S227:2:1].L = $V_qs_WR0_S71[0:2:1].L
  179.                            6[$SI_S227 + $SR_S233:2:1].L = $LCS_ps_87[0:2:1].L * $LIS_73[0:2:1].L
  175.                            6[$SI_S227 + $SR_S234:2:1].L = 6[$LIS_E74 + $SI_S227:2:1].L
  176.                            $LCS_tf_89[0:2:1].L = 6[$LIS_E75 + $SI_S227:2:1].L
  176.                            6[$SI_S227 + $SR_S235:2:1].L = $LCS_tf_89[0:2:1].L
  177.                            $V_qs_WR0_S72[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_89[0:2:1].L )
  178.                            $V_qs_WR0_S73[0:2:1].L = ( $V_qs_WR0_S72[0:2:1].L / ( $LCS_ps_87[0:2:1].L * $LIS_76[0:2:1].L + $V_qs_WR0_S72[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            6[$LIS_E77 + $SI_S227:2:1].L = $V_qs_WR0_S73[0:2:1].L
  179.                            6[$SI_S227 + $SR_S236:2:1].L = $LCS_ps_87[0:2:1].L * $LIS_78[0:2:1].L
  175.                            6[$SI_S227 + $SR_S237:2:1].L = 6[$LIS_E79 + $SI_S227:2:1].L
  176.                            $LCS_tf_90[0:2:1].L = 6[$LIS_E80 + $SI_S227:2:1].L
  176.                            6[$SI_S227 + $SR_S238:2:1].L = $LCS_tf_90[0:2:1].L
  177.                            $V_qs_WR0_S74[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_90[0:2:1].L )
  178.                            $V_qs_WR0_S75[0:2:1].L = ( $V_qs_WR0_S74[0:2:1].L / ( $LCS_ps_87[0:2:1].L * $LIS_81[0:2:1].L + $V_qs_WR0_S74[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            6[$LIS_E82 + $SI_S227:2:1].L = $V_qs_WR0_S75[0:2:1].L
  179.                            6[$SI_S227 + $SR_S239:2:1].L = $LCS_ps_87[0:2:1].L * $LIS_83[0:2:1].L
  174.                            $SI_S227 = 64 + $SI_S227
  174.                            $LC_S240 = 8 + $LC_S240
  174.                            if ( $LC_S240 >= -7 ) exit
  174.                         enddo
  174.                      endif
  174.                      if ( $LC_S240 < 0 ) then
  174. !dir$ blocking_size( 0, 0 )
  174.                         do
  175.                            0[$SI_S227 + $SR_S228:2:1].L = 0[$LIS_E61 + $SI_S227:2:1].L
  176.                            $LCS_tf_91[0:2:1].L = 0[$LIS_E62 + $SI_S227:2:1].L
  176.                            0[$SI_S227 + $SR_S229:2:1].L = $LCS_tf_91[0:2:1].L
  177.                            $V_qs_WR0_S76[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_91[0:2:1].L )
  178.                            $LCS_ps_92[0:2:1].L = 0[$LIS_S34 + $SI_S227:2:1].L
  178.                            $V_qs_WR0_S77[0:2:1].L = ( $V_qs_WR0_S76[0:2:1].L / ( $LCS_ps_92[0:2:1].L * $LIS_64[0:2:1].L + $V_qs_WR0_S76[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            0[$LIS_E67 + $SI_S227:2:1].L = $V_qs_WR0_S77[0:2:1].L
  179.                            0[$SI_S227 + $SR_S230:2:1].L = $LCS_ps_92[0:2:1].L * $LIS_68[0:2:1].L
  175.                            0[$SI_S227 + $SR_S231:2:1].L = 0[$LIS_E69 + $SI_S227:2:1].L
  176.                            $LCS_tf_93[0:2:1].L = 0[$LIS_E70 + $SI_S227:2:1].L
  176.                            0[$SI_S227 + $SR_S232:2:1].L = $LCS_tf_93[0:2:1].L
  177.                            $V_qs_WR0_S78[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_93[0:2:1].L )
  178.                            $V_qs_WR0_S79[0:2:1].L = ( $V_qs_WR0_S78[0:2:1].L / ( $LCS_ps_92[0:2:1].L * $LIS_71[0:2:1].L + $V_qs_WR0_S78[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            0[$LIS_E72 + $SI_S227:2:1].L = $V_qs_WR0_S79[0:2:1].L
  179.                            0[$SI_S227 + $SR_S233:2:1].L = $LCS_ps_92[0:2:1].L * $LIS_73[0:2:1].L
  175.                            0[$SI_S227 + $SR_S234:2:1].L = 0[$LIS_E74 + $SI_S227:2:1].L
  176.                            $LCS_tf_94[0:2:1].L = 0[$LIS_E75 + $SI_S227:2:1].L
  176.                            0[$SI_S227 + $SR_S235:2:1].L = $LCS_tf_94[0:2:1].L
  177.                            $V_qs_WR0_S80[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_94[0:2:1].L )
  178.                            $V_qs_WR0_S81[0:2:1].L = ( $V_qs_WR0_S80[0:2:1].L / ( $LCS_ps_92[0:2:1].L * $LIS_76[0:2:1].L + $V_qs_WR0_S80[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            0[$LIS_E77 + $SI_S227:2:1].L = $V_qs_WR0_S81[0:2:1].L
  179.                            0[$SI_S227 + $SR_S236:2:1].L = $LCS_ps_92[0:2:1].L * $LIS_78[0:2:1].L
  175.                            0[$SI_S227 + $SR_S237:2:1].L = 0[$LIS_E79 + $SI_S227:2:1].L
  176.                            $LCS_tf_95[0:2:1].L = 0[$LIS_E80 + $SI_S227:2:1].L
  176.                            0[$SI_S227 + $SR_S238:2:1].L = $LCS_tf_95[0:2:1].L
  177.                            $V_qs_WR0_S82[0:2:1].L = _expn( $LIS_111[0:2:1].L / $LCS_tf_95[0:2:1].L )
  178.                            $V_qs_WR0_S83[0:2:1].L = ( $V_qs_WR0_S82[0:2:1].L / ( $LCS_ps_92[0:2:1].L * $LIS_81[0:2:1].L + $V_qs_WR0_S82[0:2:1].L * $LIS_110[0:2:1].L ) * $LIS_109[0:2:1].L )
  178.                            0[$LIS_E82 + $SI_S227:2:1].L = $V_qs_WR0_S83[0:2:1].L
  179.                            0[$SI_S227 + $SR_S239:2:1].L = $LCS_ps_92[0:2:1].L * $LIS_83[0:2:1].L
  174.                            $SI_S227 = 16 + $SI_S227
  174.                            $LC_S240 = 2 + $LC_S240
  174.                            if ( $LC_S240 >= 0 ) exit
  174.                         enddo
  174.                      endif
  174.                      $I_L174_S241 = $LIS_S17
  174.                   endif
  174.                   if ( $LCS_MR_ncols_66 > $I_L174_S241 ) then !  99.50%
  175.                      $LCS_96 = $I_L174_S241 + $SR_S242
  175.                      0[t$34,$LCS_96].L = 0[$LIS_S22,$LCS_96].L
  176.                      $MR_tf_28 = 0[$LIS_S21,$LCS_96].L
  176.                      0[t$40,$LCS_96].L = $MR_tf_28
  177.                      $qs_WR0_S87 = _expn( $rlrv_S218 / $MR_tf_28 )
  178.                      $MR_ps_30 = 0[$LIS_S34,$I_L174_S241].L
  178.                      $qs_WR0_S88 = ( $qs_WR0_S87 / ( $SCA_sl#1_U0 * $MR_ps_30 + $qs_WR0_S87 * $const2_S219 ) * $const1_S220 )
  178.                      0[$LIS_S19,$LCS_96].L = $qs_WR0_S88
  179.                      0[t$22,$LCS_96].L = ( $SCA_del#1_U4 * $rgrav_S222 ) * $MR_ps_30
  175.                      $LCS_97 = $I_L174_S241 + $SR_S243
  175.                      0[t$34,$LCS_97].L = 0[$LIS_S22,$LCS_97].L
  176.                      $MR_tf_34 = 0[$LIS_S21,$LCS_97].L
  176.                      0[t$40,$LCS_97].L = $MR_tf_34
  177.                      $qs_WR0_S90 = _expn( $rlrv_S218 / $MR_tf_34 )
  178.                      $qs_WR0_S91 = ( $qs_WR0_S90 / ( $SCA_sl#2_U1 * $MR_ps_30 + $qs_WR0_S90 * $const2_S219 ) * $const1_S220 )
  178.                      0[$LIS_S19,$LCS_97].L = $qs_WR0_S91
  179.                      0[t$22,$LCS_97].L = ( $SCA_del#2_U5 * $rgrav_S222 ) * $MR_ps_30
  175.                      $LCS_98 = $I_L174_S241 + $SR_S244
  175.                      0[t$34,$LCS_98].L = 0[$LIS_S22,$LCS_98].L
  176.                      $MR_tf_39 = 0[$LIS_S21,$LCS_98].L
  176.                      0[t$40,$LCS_98].L = $MR_tf_39
  177.                      $qs_WR0_S93 = _expn( $rlrv_S218 / $MR_tf_39 )
  178.                      $qs_WR0_S94 = ( $qs_WR0_S93 / ( $SCA_sl#3_U2 * $MR_ps_30 + $qs_WR0_S93 * $const2_S219 ) * $const1_S220 )
  178.                      0[$LIS_S19,$LCS_98].L = $qs_WR0_S94
  179.                      0[t$22,$LCS_98].L = ( $SCA_del#3_U6 * $rgrav_S222 ) * $MR_ps_30
  175.                      $LCS_99 = $I_L174_S241 + $SR_S245
  175.                      0[t$34,$LCS_99].L = 0[$LIS_S22,$LCS_99].L
  176.                      $MR_tf_44 = 0[$LIS_S21,$LCS_99].L
  176.                      0[t$40,$LCS_99].L = $MR_tf_44
  177.                      $qs_WR0_S96 = _expn( $rlrv_S218 / $MR_tf_44 )
  178.                      $qs_WR0_S97 = ( $qs_WR0_S96 / ( $SCA_sl#4_U3 * $MR_ps_30 + $qs_WR0_S96 * $const2_S219 ) * $const1_S220 )
  178.                      0[$LIS_S19,$LCS_99].L = $qs_WR0_S97
  179.                      0[t$22,$LCS_99].L = ( $SCA_del#4_U7 * $rgrav_S222 ) * $MR_ps_30
  179.                   endif
  175.                   $SR_S245 = $LIS_E45 + $SR_S245
  175.                   $SR_S244 = $LIS_E45 + $SR_S244
  175.                   $SR_S243 = $LIS_E45 + $SR_S243
  175.                   $SR_S242 = $LIS_E45 + $SR_S242
  179.                   $SR_S239 = $LIS_E46 + $SR_S239
  176.                   $SR_S238 = $LIS_E46 + $SR_S238
  175.                   $SR_S223 = $LIS_E46 + $SR_S223
  175.                   $SR_S237 = $LIS_E46 + $SR_S237
  179.                   $SR_S236 = $LIS_E46 + $SR_S236
  176.                   $SR_S235 = $LIS_E46 + $SR_S235
  175.                   $SR_S224 = $LIS_E46 + $SR_S224
  175.                   $SR_S234 = $LIS_E46 + $SR_S234
  179.                   $SR_S233 = $LIS_E46 + $SR_S233
  176.                   $SR_S232 = $LIS_E46 + $SR_S232
  175.                   $SR_S225 = $LIS_E46 + $SR_S225
  175.                   $SR_S231 = $LIS_E46 + $SR_S231
  179.                   $SR_S230 = $LIS_E46 + $SR_S230
  176.                   $SR_S229 = $LIS_E46 + $SR_S229
  175.                   $SR_S226 = $LIS_E46 + $SR_S226
  175.                   $SR_S228 = $LIS_E46 + $SR_S228
  174.                   $SR_S221 = 4 + $SR_S221
  181.                   $I_L173_S246 = 1 + $I_L173_S246
  180.                   if ( $I_L173_S246 >= $LIS_E44 ) exit
  180.                enddo
  181.                $I_L173_S247 = ( and( 0xfffffffffffffffcUL, $MR_kmax_12 ) )
  181.             endif
  173.             $LCS_104 = $MR_kmax_12
  173.             if ( $I_L173_S247 < $LCS_104 ) then
  173.                $I_L173_S251 = 0
  179.                $rgrav_S252 = rgrav
  178.                $const2_S249 = const2
  178.                $const1_S248 = const1
  177.                $rlrv_S250 = rlrv
  174.                $LCS_100 = $MR_ncols_11
  174.                if ( $LCS_100 >= 2 ) then
  174.                   $TC_20 = and( -2, $LCS_100 )
  175.                   $LCS_I_L173_101 = $LCS_100 * $I_L173_S247
  175.                   $SR_S259 = $LCS_I_L173_101
  179.                   $LCS_102 = _lsh( $LCS_I_L173_101, 3 )
  179.                   $SR_S257 = t$22 + $LCS_102
  176.                   $SR_S256 = t$40 + $LCS_102
  175.                   $SR_S253 = $LCS_102
  175.                   $SR_S255 = t$34 + $LCS_102
  179.                   $LCS_MR_ncols_103 = $MR_ncols_11
  179.                   $LIS_E53 = _lsh( $LCS_MR_ncols_103, 3 )
  181.                   $LIS_S137 = $LCS_104 - $I_L173_S247
  178.                   $LIS_S110 = loc( qs )
  178.                   $LIS_50[0:2:1].L = _bcst( $const1_S248, 2 )
  178.                   $LIS_49[0:2:1].L = _bcst( $const2_S249, 2 )
  178.                   $LIS_S120 = loc( ps )
  177.                   $LIS_48[0:2:1].L = _bcst( $rlrv_S250, 2 )
  176.                   $LIS_S113 = loc( tf )
  175.                   $LIS_S114 = loc( qf )
  174.                   $LIS_E47 = -$TC_20
  174.                   $LIS_S107 = loc( del )
  174.                   $LIS_S105 = loc( sl )
  173. !dir$ blocking_size( 0, 0 )
  173.                   do
  174.                      $LCS_105 = $I_L173_S247 + $I_L173_S251
  174.                      $sl_S112 = 0[$LIS_S105,$LCS_105].L
  174.                      $del_S109 = 0[$LIS_S107,$LCS_105].L
  174.                      $LC_S258 = $LIS_E47
  174.                      $SI_S254 = 0
  179.                      $LIS_88[0:2:1].L = _bcst( $del_S109 * $rgrav_S252, 2 )
  178.                      $LIS_E87 = $LIS_S110 + $SR_S253
  178.                      $LIS_86[0:2:1].L = _bcst( $sl_S112, 2 )
  176.                      $LIS_E85 = $LIS_S113 + $SR_S253
  175.                      $LIS_E84 = $LIS_S114 + $SR_S253
  174.                      if ( $LIS_E47 < -7 ) then
  174. !dir$ blocking_size( 0, 0 )
  174.                         do
  175.                            $LCS_108 = $LIS_E84 + $SI_S254
  175.                            $LCS_109 = $SI_S254 + $SR_S255
  175.                            0[$LCS_109:2:1].L = 0[$LCS_108:2:1].L
  176.                            $LCS_110 = $LIS_E85 + $SI_S254
  176.                            $LCS_tf_106[0:2:1].L = 0[$LCS_110:2:1].L
  176.                            $LCS_111 = $SI_S254 + $SR_S256
  176.                            0[$LCS_111:2:1].L = $LCS_tf_106[0:2:1].L
  177.                            $V_qs_WR0_S119[0:2:1].L = _expn( $LIS_48[0:2:1].L / $LCS_tf_106[0:2:1].L )
  178.                            $LCS_113 = $LIS_S120 + $SI_S254
  178.                            $LCS_ps_107[0:2:1].L = 0[$LCS_113:2:1].L
  178.                            $V_qs_WR0_S121[0:2:1].L = ( $V_qs_WR0_S119[0:2:1].L / ( $LCS_ps_107[0:2:1].L * $LIS_86[0:2:1].L + $V_qs_WR0_S119[0:2:1].L * $LIS_49[0:2:1].L ) * $LIS_50[0:2:1].L )
  178.                            $LCS_114 = $LIS_E87 + $SI_S254
  178.                            0[$LCS_114:2:1].L = $V_qs_WR0_S121[0:2:1].L
  179.                            $LCS_116 = $SI_S254 + $SR_S257
  179.                            0[$LCS_116:2:1].L = $LCS_ps_107[0:2:1].L * $LIS_88[0:2:1].L
  175.                            2[$LCS_109:2:1].L = 2[$LCS_108:2:1].L
  176.                            $LCS_tf_112[0:2:1].L = 2[$LCS_110:2:1].L
  176.                            2[$LCS_111:2:1].L = $LCS_tf_112[0:2:1].L
  177.                            $V_qs_WR0_S123[0:2:1].L = _expn( $LIS_48[0:2:1].L / $LCS_tf_112[0:2:1].L )
  178.                            $LCS_ps_115[0:2:1].L = 2[$LCS_113:2:1].L
  178.                            $V_qs_WR0_S124[0:2:1].L = ( $V_qs_WR0_S123[0:2:1].L / ( $LCS_ps_115[0:2:1].L * $LIS_86[0:2:1].L + $V_qs_WR0_S123[0:2:1].L * $LIS_49[0:2:1].L ) * $LIS_50[0:2:1].L )
  178.                            2[$LCS_114:2:1].L = $V_qs_WR0_S124[0:2:1].L
  179.                            2[$LCS_116:2:1].L = $LCS_ps_115[0:2:1].L * $LIS_88[0:2:1].L
  175.                            4[$LCS_109:2:1].L = 4[$LCS_108:2:1].L
  176.                            $LCS_tf_117[0:2:1].L = 4[$LCS_110:2:1].L
  176.                            4[$LCS_111:2:1].L = $LCS_tf_117[0:2:1].L
  177.                            $V_qs_WR0_S125[0:2:1].L = _expn( $LIS_48[0:2:1].L / $LCS_tf_117[0:2:1].L )
  178.                            $LCS_ps_118[0:2:1].L = 4[$LCS_113:2:1].L
  178.                            $V_qs_WR0_S126[0:2:1].L = ( $V_qs_WR0_S125[0:2:1].L / ( $LCS_ps_118[0:2:1].L * $LIS_86[0:2:1].L + $V_qs_WR0_S125[0:2:1].L * $LIS_49[0:2:1].L ) * $LIS_50[0:2:1].L )
  178.                            4[$LCS_114:2:1].L = $V_qs_WR0_S126[0:2:1].L
  179.                            4[$LCS_116:2:1].L = $LCS_ps_118[0:2:1].L * $LIS_88[0:2:1].L
  175.                            6[$LCS_109:2:1].L = 6[$LCS_108:2:1].L
  176.                            $LCS_tf_119[0:2:1].L = 6[$LCS_110:2:1].L
  176.                            6[$LCS_111:2:1].L = $LCS_tf_119[0:2:1].L
  177.                            $V_qs_WR0_S127[0:2:1].L = _expn( $LIS_48[0:2:1].L / $LCS_tf_119[0:2:1].L )
  178.                            $LCS_ps_120[0:2:1].L = 6[$LCS_113:2:1].L
  178.                            $V_qs_WR0_S128[0:2:1].L = ( $V_qs_WR0_S127[0:2:1].L / ( $LCS_ps_120[0:2:1].L * $LIS_86[0:2:1].L + $V_qs_WR0_S127[0:2:1].L * $LIS_49[0:2:1].L ) * $LIS_50[0:2:1].L )
  178.                            6[$LCS_114:2:1].L = $V_qs_WR0_S128[0:2:1].L
  179.                            6[$LCS_116:2:1].L = $LCS_ps_120[0:2:1].L * $LIS_88[0:2:1].L
  174.                            $SI_S254 = 64 + $SI_S254
  174.                            $LC_S258 = 8 + $LC_S258
  174.                            if ( $LC_S258 >= -7 ) exit
  174.                         enddo
  174.                      endif
  174.                      if ( $LC_S258 < 0 ) then
  174. !dir$ blocking_size( 0, 0 )
  174.                         do
  175.                            0[$SI_S254 + $SR_S255:2:1].L = 0[$LIS_E84 + $SI_S254:2:1].L
  176.                            $LCS_tf_121[0:2:1].L = 0[$LIS_E85 + $SI_S254:2:1].L
  176.                            0[$SI_S254 + $SR_S256:2:1].L = $LCS_tf_121[0:2:1].L
  177.                            $V_qs_WR0_S129[0:2:1].L = _expn( $LIS_48[0:2:1].L / $LCS_tf_121[0:2:1].L )
  178.                            $LCS_ps_122[0:2:1].L = 0[$LIS_S120 + $SI_S254:2:1].L
  178.                            $V_qs_WR0_S130[0:2:1].L = ( $V_qs_WR0_S129[0:2:1].L / ( $LCS_ps_122[0:2:1].L * $LIS_86[0:2:1].L + $V_qs_WR0_S129[0:2:1].L * $LIS_49[0:2:1].L ) * $LIS_50[0:2:1].L )
  178.                            0[$LIS_E87 + $SI_S254:2:1].L = $V_qs_WR0_S130[0:2:1].L
  179.                            0[$SI_S254 + $SR_S257:2:1].L = $LCS_ps_122[0:2:1].L * $LIS_88[0:2:1].L
  174.                            $SI_S254 = 16 + $SI_S254
  174.                            $LC_S258 = 2 + $LC_S258
  174.                            if ( $LC_S258 >= 0 ) exit
  174.                         enddo
  174.                      endif
  174.                      if ( $LCS_MR_ncols_103 > $TC_20 ) then !  99.50%
  175.                         $LCS_123 = $TC_20 + $SR_S259
  175.                         0[t$34,$LCS_123].L = 0[$LIS_S114,$LCS_123].L
  176.                         $MR_tf_51 = 0[$LIS_S113,$LCS_123].L
  176.                         0[t$40,$LCS_123].L = $MR_tf_51
  177.                         $qs_WR0_S134 = _expn( $rlrv_S250 / $MR_tf_51 )
  178.                         $MR_ps_53 = 0[$LIS_S120,$TC_20].L
  178.                         $qs_WR0_S135 = ( $qs_WR0_S134 / ( $sl_S112 * $MR_ps_53 + $qs_WR0_S134 * $const2_S249 ) * $const1_S248 )
  178.                         0[$LIS_S110,$LCS_123].L = $qs_WR0_S135
  179.                         0[t$22,$LCS_123].L = ( $del_S109 * $rgrav_S252 ) * $MR_ps_53
  179.                      endif
  175.                      $SR_S259 = $LCS_MR_ncols_103 + $SR_S259
  179.                      $SR_S257 = $LIS_E53 + $SR_S257
  176.                      $SR_S256 = $LIS_E53 + $SR_S256
  175.                      $SR_S253 = $LIS_E53 + $SR_S253
  175.                      $SR_S255 = $LIS_E53 + $SR_S255
  181.                      $I_L173_S251 = 1 + $I_L173_S251
  180.                      if ( $I_L173_S251 >= $LIS_S137 ) exit
  180.                   enddo
  180.                else
  174.                   $I_L174_S138 = 0
  175.                   $SR_S260 = $MR_ncols_11 * $I_L173_S247 + $I_L174_S138
  175.                   $LIS_S149 = $MR_ncols_11
  181.                   $LIS_S150 = $MR_kmax_12 - $I_L173_S247
  178.                   $LIS_S147 = loc( qs )
  176.                   $LIS_S143 = loc( tf )
  175.                   $LIS_S141 = loc( qf )
  174.                   $LIS_S140 = loc( del )
  174.                   $LIS_S139 = loc( sl )
  173. !dir$ blocking_size( 0, 0 )
  173.                   do
  174.                      $LCS_124 = $I_L173_S247 + $I_L173_S251
  174.                      $sl_S145 = 0[$LIS_S139,$LCS_124].L
  174.                      $del_S148 = 0[$LIS_S140,$LCS_124].L
  174.                      if ( $MR_ncols_11 > $I_L174_S138 ) then !  99.50%
  175.                         0[t$34,$SR_S260].L = 0[$LIS_S141,$SR_S260].L
  176.                         $MR_tf_59 = 0[$LIS_S143,$SR_S260].L
  176.                         0[t$40,$SR_S260].L = $MR_tf_59
  177.                         $qs_WR0_S144 = _expn( $rlrv_S250 / $MR_tf_59 )
  178.                         $MR_ps_61 = 0[loc( ps ),$I_L174_S138].L
  178.                         $qs_WR0_S146 = ( $qs_WR0_S144 / ( $sl_S145 * $MR_ps_61 + $qs_WR0_S144 * $const2_S249 ) * $const1_S248 )
  178.                         0[$LIS_S147,$SR_S260].L = $qs_WR0_S146
  179.                         0[t$22,$SR_S260].L = ( $del_S148 * $rgrav_S252 ) * $MR_ps_61
  179.                      endif
  175.                      $SR_S260 = $LIS_S149 + $SR_S260
  181.                      $I_L173_S251 = 1 + $I_L173_S251
  180.                      if ( $I_L173_S251 >= $LIS_S150 ) exit
  180.                   enddo
  180.                endif
  180.             endif
  180.          endif
  180.       endif
  183.       $LCS_MR_ncols_125 = $MR_ncols_11
  183.       $F_A33 = $LCS_MR_ncols_125
  183.       if ( $MR_ncols_11 > 0 ) then !  99.50%
  183.          $I_L183_S262 = 0
  183.          $SR_S261 = 0
  183.          do
  183.             $W0 = 0.0
  183.             __dset_cce( 0[t$31,$SR_S261].L, $W0, $F_A33 )
  183.             $SR_S261 = $LCS_MR_ncols_125 + $SR_S261
  183.             $I_L183_S262 = 1 + $I_L183_S262
  183.             if ( $I_L183_S262 >= 2 ) exit
  183.          enddo
  183.       endif
  187.       $rhsat_S278 = 8.0000000000000004e-1
  189.       if ( $MR_kmax_12 > 0 ) then
  189.          $I_L189_S263 = 0
  200.          $SC_rlocp_I9 = rlocp
  198.          $SC_xx1_I8 = xx1
  193.          $SR_S269 = 0
  202.          $LCS_128 = $MR_ncols_11
  202.          $LCS_MR_kmax_129 = $MR_kmax_12
  202.          $LCS_126 = $LCS_128 * ( -8 + _lsh( $LCS_MR_kmax_129, 3 ) )
  202.          $SR_S266 = t$22 + $LCS_126
  193.          $SR_S264 = $LCS_126
  202.          $LCS_MR_ncols_127 = $MR_ncols_11
  202.          $LIS_E60 = -_lsh( $LCS_MR_ncols_127, 3 )
  209.          $LIS_E59 = -1 + $LCS_128
  193.          $LCS_1_130 = -1 + $MR_kmax_12
  193.          $LIS_E58 = $LCS_128 * $LCS_1_130
  198.          $LIS_S160 = loc( tf )
  193.          $LIS_S162 = loc( qs )
  193.          $LIS_S163 = loc( qf )
  192.          $LIS_S159 = and( -2, $LCS_128 )
  191.          $LIS_E55 = 9.0000000000000002e-1
  192.          $LIS_E113 = -$LIS_S159
  198.          $LIS_E112 = 1.0
  189.          do
  191.             if ( $LCS_MR_kmax_129 - $I_L189_S263 == 1 ) then
  191.                $rhsat_S278 = $LIS_E55
  191.             endif
  192.             if ( $MR_ncols_11 > 0 ) then
  192.                $I_L192_S268 = 0
  193.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  193.                   $LB_Y0 = 1
  193.                   $UB_Y1 = $LCS_MR_kmax_129
  193.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  193.                   _bounds_error( $_File_Y40, $Line_Y233, $_Name_Y232, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y234 )
  193.                endif
  193.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  193.                   $LB_Y0 = 1
  193.                   $UB_Y1 = $LCS_MR_kmax_129
  193.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  193.                   _bounds_error( $_File_Y40, $Line_Y233, $_Name_Y237, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y238 )
  193.                endif
  198.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  198.                   $LB_Y0 = 1
  198.                   $UB_Y1 = $LCS_MR_kmax_129
  198.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  198.                   _bounds_error( $_File_Y40, $Line_Y243, $_Name_Y232, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y244 )
  198.                endif
  198.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  198.                   $LB_Y0 = 1
  198.                   $UB_Y1 = $LCS_MR_kmax_129
  198.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  198.                   _bounds_error( $_File_Y40, $Line_Y243, $_Name_Y246, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y247 )
  198.                endif
  198.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  198.                   $LB_Y0 = 1
  198.                   $UB_Y1 = $LCS_MR_kmax_129
  198.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  198.                   _bounds_error( $_File_Y40, $Line_Y243, $_Name_Y246, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y247 )
  198.                endif
  200.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  200.                   $LB_Y0 = 1
  200.                   $UB_Y1 = $LCS_MR_kmax_129
  200.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  200.                   _bounds_error( $_File_Y40, $Line_Y252, $_Name_Y246, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y253 )
  200.                endif
  200.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  200.                   $LB_Y0 = 1
  200.                   $UB_Y1 = $LCS_MR_kmax_129
  200.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  200.                   _bounds_error( $_File_Y40, $Line_Y252, $_Name_Y246, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y253 )
  200.                endif
  201.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  201.                   $LB_Y0 = 1
  201.                   $UB_Y1 = $LCS_MR_kmax_129
  201.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  201.                   _bounds_error( $_File_Y40, $Line_Y257, $_Name_Y237, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y258 )
  201.                endif
  201.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  201.                   $LB_Y0 = 1
  201.                   $UB_Y1 = $LCS_MR_kmax_129
  201.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  201.                   _bounds_error( $_File_Y40, $Line_Y257, $_Name_Y237, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y258 )
  201.                endif
  202.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  202.                   $LB_Y0 = 1
  202.                   $UB_Y1 = $LCS_MR_kmax_129
  202.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  202.                   _bounds_error( $_File_Y40, $Line_Y263, $_Name_Y262, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y264 )
  202.                endif
  192.                if ( $MR_ncols_11 >= 2 ) then !  99.50%
  192.                   $LC_S267 = $LIS_E113
  192.                   $SI_S265 = 0
  200.                   $LIS_95[0:2:1].L = _bcst( $SC_rlocp_I9, 2 )
  198.                   $LIS_94[0:2:1].L = _bcst( 1.0, 2 )
  198.                   $LIS_93[0:2:1].L = _bcst( $SC_xx1_I8, 2 )
  198.                   $LIS_E92 = $LIS_S160 + $SR_S264
  198.                   $LIS_91[0:2:1].L = _bcst( 0.0, 2 )
  193.                   $LIS_E90 = $LIS_S162 + $SR_S264
  193.                   $LIS_E89 = $LIS_S163 + $SR_S264
  192.                   if ( $LIS_E113 < -7 ) then
  192.                      do
  193.                         $LCS_137 = $LIS_E90 + $SI_S265
  193.                         $LCS_qs_132[0:2:1].L = 0[$LCS_137:2:1].L
  193.                         $LCS_135 = $LIS_E89 + $SI_S265
  193.                         $LCS_qf_134[0:2:1].L = 0[$LCS_135:2:1].L
  193.                         $V_super_WR0_S166[0:2:1].L = $LCS_qf_134[0:2:1].L - $LCS_qs_132[0:2:1].L
  193.                         $LCS_138 = t$37 + $SI_S265
  193.                         0[$LCS_138:2:1].L = $V_super_WR0_S166[0:2:1].L
  198.                         $LCS_133 = $LIS_E92 + $SI_S265
  198.                         $LCS_tf_131[0:2:1].L = 0[$LCS_133:2:1].L
  198.                         $V_qcond_S167[0:2:1].L = max( $LIS_91[0:2:1].L, $V_super_WR0_S166[0:2:1].L ) / ( $LIS_94[0:2:1].L - ( $LCS_qs_132[0:2:1].L / ( $LCS_tf_131[0:2:1].L * $LCS_tf_131[0:2:1].L ) * $LIS_93[0:2:1].L ) )
  200.                         $CS_0[0:2:1].L = ( max( $LIS_91[0:2:1].L, $V_qcond_S167[0:2:1].L ) )
  200.                         0[$LCS_133:2:1].L = $CS_0[0:2:1].L * $LIS_95[0:2:1].L + $LCS_tf_131[0:2:1].L
  201.                         0[$LCS_135:2:1].L = $LCS_qf_134[0:2:1].L - $CS_0[0:2:1].L
  202.                         $LCS_136 = t$31 + $SI_S265
  202.                         $LCS_142 = $SI_S265 + $SR_S266
  202.                         0[$LCS_136:2:1].L = 0[$LCS_142:2:1].L * $CS_0[0:2:1].L + 0[$LCS_136:2:1].L
  193.                         $LCS_qs_140[0:2:1].L = 2[$LCS_137:2:1].L
  193.                         $LCS_qf_141[0:2:1].L = 2[$LCS_135:2:1].L
  193.                         $V_super_WR0_S169[0:2:1].L = $LCS_qf_141[0:2:1].L - $LCS_qs_140[0:2:1].L
  193.                         2[$LCS_138:2:1].L = $V_super_WR0_S169[0:2:1].L
  198.                         $LCS_tf_139[0:2:1].L = 2[$LCS_133:2:1].L
  198.                         $V_qcond_S170[0:2:1].L = max( $LIS_91[0:2:1].L, $V_super_WR0_S169[0:2:1].L ) / ( $LIS_94[0:2:1].L - ( $LCS_qs_140[0:2:1].L / ( $LCS_tf_139[0:2:1].L * $LCS_tf_139[0:2:1].L ) * $LIS_93[0:2:1].L ) )
  200.                         $CS_1[0:2:1].L = ( max( $LIS_91[0:2:1].L, $V_qcond_S170[0:2:1].L ) )
  200.                         2[$LCS_133:2:1].L = $CS_1[0:2:1].L * $LIS_95[0:2:1].L + $LCS_tf_139[0:2:1].L
  201.                         2[$LCS_135:2:1].L = $LCS_qf_141[0:2:1].L - $CS_1[0:2:1].L
  202.                         2[$LCS_136:2:1].L = 2[$LCS_142:2:1].L * $CS_1[0:2:1].L + 2[$LCS_136:2:1].L
  193.                         $LCS_qs_144[0:2:1].L = 4[$LCS_137:2:1].L
  193.                         $LCS_qf_145[0:2:1].L = 4[$LCS_135:2:1].L
  193.                         $V_super_WR0_S171[0:2:1].L = $LCS_qf_145[0:2:1].L - $LCS_qs_144[0:2:1].L
  193.                         4[$LCS_138:2:1].L = $V_super_WR0_S171[0:2:1].L
  198.                         $LCS_tf_143[0:2:1].L = 4[$LCS_133:2:1].L
  198.                         $V_qcond_S172[0:2:1].L = max( $LIS_91[0:2:1].L, $V_super_WR0_S171[0:2:1].L ) / ( $LIS_94[0:2:1].L - ( $LCS_qs_144[0:2:1].L / ( $LCS_tf_143[0:2:1].L * $LCS_tf_143[0:2:1].L ) * $LIS_93[0:2:1].L ) )
  200.                         $CS_2[0:2:1].L = ( max( $LIS_91[0:2:1].L, $V_qcond_S172[0:2:1].L ) )
  200.                         4[$LCS_133:2:1].L = $CS_2[0:2:1].L * $LIS_95[0:2:1].L + $LCS_tf_143[0:2:1].L
  201.                         4[$LCS_135:2:1].L = $LCS_qf_145[0:2:1].L - $CS_2[0:2:1].L
  202.                         4[$LCS_136:2:1].L = 4[$LCS_142:2:1].L * $CS_2[0:2:1].L + 4[$LCS_136:2:1].L
  193.                         $LCS_qs_147[0:2:1].L = 6[$LCS_137:2:1].L
  193.                         $LCS_qf_148[0:2:1].L = 6[$LCS_135:2:1].L
  193.                         $V_super_WR0_S173[0:2:1].L = $LCS_qf_148[0:2:1].L - $LCS_qs_147[0:2:1].L
  193.                         6[$LCS_138:2:1].L = $V_super_WR0_S173[0:2:1].L
  198.                         $LCS_tf_146[0:2:1].L = 6[$LCS_133:2:1].L
  198.                         $V_qcond_S174[0:2:1].L = max( $LIS_91[0:2:1].L, $V_super_WR0_S173[0:2:1].L ) / ( $LIS_94[0:2:1].L - ( $LCS_qs_147[0:2:1].L / ( $LCS_tf_146[0:2:1].L * $LCS_tf_146[0:2:1].L ) * $LIS_93[0:2:1].L ) )
  200.                         $CS_3[0:2:1].L = ( max( $LIS_91[0:2:1].L, $V_qcond_S174[0:2:1].L ) )
  200.                         6[$LCS_133:2:1].L = $CS_3[0:2:1].L * $LIS_95[0:2:1].L + $LCS_tf_146[0:2:1].L
  201.                         6[$LCS_135:2:1].L = $LCS_qf_148[0:2:1].L - $CS_3[0:2:1].L
  202.                         6[$LCS_136:2:1].L = 6[$LCS_142:2:1].L * $CS_3[0:2:1].L + 6[$LCS_136:2:1].L
  192.                         $SI_S265 = 64 + $SI_S265
  192.                         $LC_S267 = 8 + $LC_S267
  192.                         if ( $LC_S267 >= -7 ) exit
  192.                      enddo
  192.                   endif
  192.                   if ( $LC_S267 < 0 ) then
  192.                      do
  193.                         $LCS_qs_150[0:2:1].L = 0[$LIS_E90 + $SI_S265:2:1].L
  193.                         $LCS_153 = $LIS_E89 + $SI_S265
  193.                         $LCS_qf_152[0:2:1].L = 0[$LCS_153:2:1].L
  193.                         $V_super_WR0_S175[0:2:1].L = $LCS_qf_152[0:2:1].L - $LCS_qs_150[0:2:1].L
  193.                         0[t$37 + $SI_S265:2:1].L = $V_super_WR0_S175[0:2:1].L
  198.                         $LCS_151 = $LIS_E92 + $SI_S265
  198.                         $LCS_tf_149[0:2:1].L = 0[$LCS_151:2:1].L
  198.                         $V_qcond_S176[0:2:1].L = max( $LIS_91[0:2:1].L, $V_super_WR0_S175[0:2:1].L ) / ( $LIS_94[0:2:1].L - ( $LCS_qs_150[0:2:1].L / ( $LCS_tf_149[0:2:1].L * $LCS_tf_149[0:2:1].L ) * $LIS_93[0:2:1].L ) )
  200.                         $CS_4[0:2:1].L = ( max( $LIS_91[0:2:1].L, $V_qcond_S176[0:2:1].L ) )
  200.                         0[$LCS_151:2:1].L = $CS_4[0:2:1].L * $LIS_95[0:2:1].L + $LCS_tf_149[0:2:1].L
  201.                         0[$LCS_153:2:1].L = $LCS_qf_152[0:2:1].L - $CS_4[0:2:1].L
  202.                         $LCS_154 = t$31 + $SI_S265
  202.                         0[$LCS_154:2:1].L = 0[$SI_S265 + $SR_S266:2:1].L * $CS_4[0:2:1].L + 0[$LCS_154:2:1].L
  192.                         $SI_S265 = 16 + $SI_S265
  192.                         $LC_S267 = 2 + $LC_S267
  192.                         if ( $LC_S267 >= 0 ) exit
  192.                      enddo
  192.                   endif
  192.                   $I_L192_S268 = $LIS_S159
  192.                endif
  192.                if ( $LCS_MR_ncols_127 > $I_L192_S268 ) then !  99.50%
  193.                   $LCS_155 = $LIS_E58 + $I_L192_S268 - $SR_S269
  193.                   $MR_qs_65 = 0[$LIS_S162,$LCS_155].L
  193.                   $MR_qf_S270 = 0[$LIS_S163,$LCS_155].L
  193.                   $super_WR0_R1 = $MR_qf_S270 - $MR_qs_65
  193.                   0[t$37,$I_L192_S268].L = $super_WR0_R1
  198.                   $MR_tf_S271 = 0[$LIS_S160,$LCS_155].L
  198.                   $qcond_S4 = max( 0.0, $super_WR0_R1 ) / ( $LIS_E112 - ( $MR_qs_65 / ( $MR_tf_S271 * $MR_tf_S271 ) * $SC_xx1_I8 ) )
  200.                   $LCS_156 = ( max( 0.0, $qcond_S4 ) )
  200.                   $MR_tf_S272 = $MR_tf_S271 + $LCS_156 * $SC_rlocp_I9
  200.                   0[$LIS_S160,$LCS_155].L = $MR_tf_S272
  201.                   $MR_qf_S273 = $MR_qf_S270 - $LCS_156
  201.                   0[$LIS_S163,$LCS_155].L = $MR_qf_S273
  202.                   $MR_dpovg_68 = 0[t$22,$LCS_155].L
  202.                   $MR_prec_S274 = 0[t$31,$I_L192_S268].L
  202.                   $MR_prec_S275 = $MR_prec_S274 + $LCS_156 * $MR_dpovg_68
  202.                   0[t$31,$I_L192_S268].L = $MR_prec_S275
  202.                endif
  202.             endif
  207.             $F_A34 = $LCS_MR_ncols_127
  207.             if ( $MR_ncols_11 > 0 ) then !  99.50%
  207.                $W2 = 0.0
  207.                __dset_cce( 0[t$25,0].L, $W2, $F_A34 )
  208.                $I_L208_S276 = 0
  212.                $LIS_E98 = 3.2000000000000001e-1 * $dtsqrt_S8
  210.                $LIS_S182 = $LIS_E58 - $SR_S269
  210.                $LIS_S181 = $LCS_MR_kmax_129 - $I_L189_S263
  208.                do
  209.                   if ( 0[t$37,$I_L208_S276].L <= 0.0 ) then
  209.                      if ( $LIS_E59 - $I_L208_S276 < 0 ) then
  209.                         $LB_Y0 = 1
  209.                         $UB_Y1 = $LCS_MR_ncols_127
  209.                         $Subscript_Y5 = 1 + $I_L208_S276
  209.                         _bounds_error( $_File_Y40, $Line_Y274, $_Name_Y276, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y277 )
  209.                      endif
  209.                      $MR_prec_S277 = 0[t$31,$I_L208_S276].L
  209.                      if ( $MR_prec_S277 > 0.0 ) then
  210.                         if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  210.                            $LB_Y0 = 1
  210.                            $UB_Y1 = $LCS_MR_kmax_129
  210.                            $Subscript_Y5 = $LIS_S181
  210.                            _bounds_error( $_File_Y40, $Line_Y278, $_Name_Y237, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y279 )
  210.                         endif
  210.                         if ( $LIS_E59 - $I_L208_S276 < 0 ) then
  210.                            $LB_Y0 = 1
  210.                            $UB_Y1 = $LCS_MR_ncols_127
  210.                            $Subscript_Y5 = 1 + $I_L208_S276
  210.                            _bounds_error( $_File_Y40, $Line_Y278, $_Name_Y280, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y281 )
  210.                         endif
  210.                         if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  210.                            $LB_Y0 = 1
  210.                            $UB_Y1 = $LCS_MR_kmax_129
  210.                            $Subscript_Y5 = $LIS_S181
  210.                            _bounds_error( $_File_Y40, $Line_Y278, $_Name_Y232, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y282 )
  210.                         endif
  210.                         if ( $LIS_E59 - $I_L208_S276 < 0 ) then
  210.                            $LB_Y0 = 1
  210.                            $UB_Y1 = $LCS_MR_ncols_127
  210.                            $Subscript_Y5 = 1 + $I_L208_S276
  210.                            _bounds_error( $_File_Y40, $Line_Y278, $_Name_Y283, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y284 )
  210.                         endif
  210.                         if ( $LIS_E59 - $I_L208_S276 < 0 ) then
  210.                            $LB_Y0 = 1
  210.                            $UB_Y1 = $LCS_MR_ncols_127
  210.                            $Subscript_Y5 = 1 + $I_L208_S276
  210.                            _bounds_error( $_File_Y40, $Line_Y278, $_Name_Y285, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y286 )
  210.                         endif
  210.                         $LCS_157 = $LIS_S182 + $I_L208_S276
  210.                         0[t$25,$I_L208_S276].L = 0[$LIS_S162,$LCS_157].L * $rhsat_S278 - 0[$LIS_S163,$LCS_157].L
  210.                      endif
  210.                   endif
  212.                   $MR_prec_S279 = 0[t$31,$I_L208_S276].L
  212.                   0[t$28,$I_L208_S276].L = _sqrt( $MR_prec_S279 ) * $LIS_E98
  213.                   $I_L208_S276 = 1 + $I_L208_S276
  211.                   if ( $I_L208_S276 >= $LCS_MR_ncols_127 ) exit
  211.                enddo
  211.             endif
  215.             $F_A35 = $LCS_MR_ncols_127
  215.             if ( $MR_ncols_11 > 0 ) then !  99.50%
  215.                $I_L215_S281 = 0
  215.                $SR_S280 = 0
  215.                do
  215.                   $W4 = 0.0
  215.                   __dset_cce( 0[t$19,$SR_S280].L, $W4, $F_A35 )
  215.                   $SR_S280 = $LCS_MR_ncols_127 + $SR_S280
  215.                   $I_L215_S281 = 1 + $I_L215_S281
  215.                   if ( $I_L215_S281 >= 2 ) exit
  215.                enddo
  217.                $I_L217_S282 = 0
  226.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  226.                   $LB_Y0 = 1
  226.                   $UB_Y1 = $LCS_MR_kmax_129
  226.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  226.                   _bounds_error( $_File_Y40, $Line_Y316, $_Name_Y232, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y317 )
  226.                endif
  226.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  226.                   $LB_Y0 = 1
  226.                   $UB_Y1 = $LCS_MR_kmax_129
  226.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  226.                   _bounds_error( $_File_Y40, $Line_Y316, $_Name_Y246, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y320 )
  226.                endif
  226.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  226.                   $LB_Y0 = 1
  226.                   $UB_Y1 = $LCS_MR_kmax_129
  226.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  226.                   _bounds_error( $_File_Y40, $Line_Y316, $_Name_Y246, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y320 )
  226.                endif
  228.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  228.                   $LB_Y0 = 1
  228.                   $UB_Y1 = $LCS_MR_kmax_129
  228.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  228.                   _bounds_error( $_File_Y40, $Line_Y325, $_Name_Y246, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y326 )
  228.                endif
  228.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  228.                   $LB_Y0 = 1
  228.                   $UB_Y1 = $LCS_MR_kmax_129
  228.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  228.                   _bounds_error( $_File_Y40, $Line_Y325, $_Name_Y246, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y326 )
  228.                endif
  229.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  229.                   $LB_Y0 = 1
  229.                   $UB_Y1 = $LCS_MR_kmax_129
  229.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  229.                   _bounds_error( $_File_Y40, $Line_Y330, $_Name_Y237, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y331 )
  229.                endif
  229.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  229.                   $LB_Y0 = 1
  229.                   $UB_Y1 = $LCS_MR_kmax_129
  229.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  229.                   _bounds_error( $_File_Y40, $Line_Y330, $_Name_Y237, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y331 )
  229.                endif
  231.                if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  231.                   $LB_Y0 = 1
  231.                   $UB_Y1 = $LCS_MR_kmax_129
  231.                   $Subscript_Y5 = $LCS_MR_kmax_129 - $I_L189_S263
  231.                   _bounds_error( $_File_Y40, $Line_Y336, $_Name_Y262, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y337 )
  231.                endif
  220.                $LIS_S189 = $LIS_E58 - $SR_S269
  220.                $LIS_S188 = $LCS_MR_kmax_129 - $I_L189_S263
  217.                do
  218.                   $MR_evap_76 = 0[t$25,$I_L217_S282].L
  218.                   if ( $MR_evap_76 > 0.0 ) then
  219.                      if ( $LIS_E59 - $I_L217_S282 < 0 ) then
  219.                         $LB_Y0 = 1
  219.                         $UB_Y1 = $LCS_MR_ncols_127
  219.                         $Subscript_Y5 = 1 + $I_L217_S282
  219.                         _bounds_error( $_File_Y40, $Line_Y297, $_Name_Y294, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y298 )
  219.                      endif
  219.                      if ( $LIS_E59 - $I_L217_S282 < 0 ) then
  219.                         $LB_Y0 = 1
  219.                         $UB_Y1 = $LCS_MR_ncols_127
  219.                         $Subscript_Y5 = 1 + $I_L217_S282
  219.                         _bounds_error( $_File_Y40, $Line_Y297, $_Name_Y299, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y300 )
  219.                      endif
  219.                      if ( $LIS_E59 - $I_L217_S282 < 0 ) then
  219.                         $LB_Y0 = 1
  219.                         $UB_Y1 = $LCS_MR_ncols_127
  219.                         $Subscript_Y5 = 1 + $I_L217_S282
  219.                         _bounds_error( $_File_Y40, $Line_Y297, $_Name_Y301, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y302 )
  219.                      endif
  219.                      $MR_amtevp_S283 = 0[t$28,$I_L217_S282].L * $MR_evap_76
  219.                      0[t$19,$LCS_MR_ncols_127 + $I_L217_S282].L = $MR_amtevp_S283
  220.                      if ( $LCS_1_130 - $I_L189_S263 < 0 ) then
  220.                         $LB_Y0 = 1
  220.                         $UB_Y1 = $LCS_MR_kmax_129
  220.                         $Subscript_Y5 = $LIS_S188
  220.                         _bounds_error( $_File_Y40, $Line_Y303, $_Name_Y262, $Dim_Y9, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y304 )
  220.                      endif
  220.                      if ( $LIS_E59 - $I_L217_S282 < 0 ) then
  220.                         $LB_Y0 = 1
  220.                         $UB_Y1 = $LCS_MR_ncols_127
  220.                         $Subscript_Y5 = 1 + $I_L217_S282
  220.                         _bounds_error( $_File_Y40, $Line_Y303, $_Name_Y305, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y306 )
  220.                      endif
  220.                      if ( $LIS_E59 - $I_L217_S282 < 0 ) then
  220.                         $LB_Y0 = 1
  220.                         $UB_Y1 = $LCS_MR_ncols_127
  220.                         $Subscript_Y5 = 1 + $I_L217_S282
  220.                         _bounds_error( $_File_Y40, $Line_Y303, $_Name_Y307, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y308 )
  220.                      endif
  220.                      if ( $LIS_E59 - $I_L217_S282 < 0 ) then
  220.                         $LB_Y0 = 1
  220.                         $UB_Y1 = $LCS_MR_ncols_127
  220.                         $Subscript_Y5 = 1 + $I_L217_S282
  220.                         _bounds_error( $_File_Y40, $Line_Y303, $_Name_Y309, $Dim_Y8, $LB_Y0, $UB_Y1, $Subscript_Y5, $Err_count_Y310 )
  220.                      endif
  220.                      $MR_dpovg_S284 = 0[t$22,$LIS_S189 + $I_L217_S282].L
  220.                      $MR_prec_S285 = 0[t$31,$I_L217_S282].L
  220.                      $MR_prec_S286 = $MR_prec_S285 / $MR_dpovg_S284
  220.                      0[t$31,$LCS_MR_ncols_127 + $I_L217_S282].L = $MR_prec_S286
  220.                   endif
  222.                   $LCS_158 = $LCS_MR_ncols_127 + $I_L217_S282
  222.                   $MR_amtevp_S288 = 0[t$19,$LCS_158].L
  222.                   $MR_prec_S287 = 0[t$31,$LCS_158].L
  222.                   $LCS_159 = min( $MR_prec_S287, $MR_amtevp_S288 )
  222.                   0[t$19,$I_L217_S282].L = $LCS_159
  226.                   $LCS_160 = $LIS_S189 + $I_L217_S282
  226.                   $MR_tf_S289 = 0[$LIS_S160,$LCS_160].L
  226.                   $qevap_S10 = max( 0.0, $LCS_159 ) / ( $LIS_E112 - ( 0[$LIS_S162,$LCS_160].L / ( $MR_tf_S289 * $MR_tf_S289 ) * $SC_xx1_I8 ) )
  228.                   $MR_tf_S290 = $MR_tf_S289 - $qevap_S10 * $SC_rlocp_I9
  228.                   0[$LIS_S160,$LCS_160].L = $MR_tf_S290
  229.                   $MR_qf_S291 = 0[$LIS_S163,$LCS_160].L
  229.                   $MR_qf_S292 = $MR_qf_S291 + $qevap_S10
  229.                   0[$LIS_S163,$LCS_160].L = $MR_qf_S292
  231.                   $MR_dpovg_S293 = 0[t$22,$LCS_160].L
  231.                   $MR_prec_S294 = 0[t$31,$I_L217_S282].L
  231.                   $MR_prec_S295 = max( 0.0, $MR_prec_S294 - $qevap_S10 * $MR_dpovg_S293 )
  231.                   0[t$31,$I_L217_S282].L = $MR_prec_S295
  232.                   $I_L217_S282 = 1 + $I_L217_S282
  221.                   if ( $I_L217_S282 >= $LCS_MR_ncols_127 ) exit
  221.                enddo
  221.             endif
  193.             $SR_S269 = $LCS_MR_ncols_127 + $SR_S269
  202.             $SR_S266 = $LIS_E60 + $SR_S266
  193.             $SR_S264 = $LIS_E60 + $SR_S264
  234.             $I_L189_S263 = 1 + $I_L189_S263
  232.             if ( $I_L189_S263 >= $LCS_MR_kmax_129 ) exit
  232.          enddo
  232.       endif
  238.       if ( 0[loc( mlrg ),0] == 1 ) then
  242.          if ( $MR_ncols_11 > 0 ) then
  242.             $I_L242_S296 = 0
  244.             $SC_latco_I10 = 0[loc( latco ),0]
  247.             $LIS_S211 = loc( qf )
  245.             $LIS_S202 = loc( tf )
  244.             $LCS_MR_ncols_161 = $MR_ncols_11
  244.             $LIS_S198 = $MR_kmax_12
  242.             do
  243.                if ( 0[t$31,$I_L242_S296].L > 0.0 ) then
  244.                   $nfprt_S297 = nfprt
  244.                   $Unit_temp_O0 = $nfprt_S297
  244.                   $_StackCntrl_O18 = $_StaticCntrl_O17
  244.                   $MR_StackCntrl_S298 = loc( $Unit_temp_O0 )
  244.                   (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S298
  244.                   _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $StaticIolist_O19[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  244.                   $nfprt_S299 = nfprt
  244.                   $Unit_temp_O1 = $nfprt_S299
  244.                   $_IOitem_P0[0] = ( 1 + $I_L242_S296 )
  244.                   (1,$_IOitem_P0)[0] = $SC_latco_I10
  244.                   $_StackCntrl_O18 = $_StaticCntrl_O21
  244.                   $MR_StackCntrl_S300 = loc( $Unit_temp_O1 )
  244.                   (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S300
  244.                   $LCS_IOitem_162 = loc( $_IOitem_P0[0] )
  244.                   $_StackDv_P10[0].L = pointer to array[1] of integer( $LCS_IOitem_162 )
  244.                   (1,$_StackDv_P10)[0].L = 32
  244.                   (2,$_StackDv_P10)[0].L = and( 0xfffffffffffffffeUL, (2,$_StackDv_P10)[0].L )
  244.                   (2,$_StackDv_P10)[0].L = and( 0xfffffffffffffffdUL, (2,$_StackDv_P10)[0].L )
  244.                   (2,$_StackDv_P10)[0].L = and( 0xfffffffffffffff3UL, (2,$_StackDv_P10)[0].L )
  244.                   (2,$_StackDv_P10)[0].L = and( 0xffffffffffffffefUL, (2,$_StackDv_P10)[0].L )
  244.                   (2,$_StackDv_P10)[0].L = or( 64, notand( 2016, (2,$_StackDv_P10)[0].L ) )
  244.                   (2,$_StackDv_P10)[0].L = or( 65536, notand( 522240, (2,$_StackDv_P10)[0].L ) )
  244.                   (2,$_StackDv_P10)[0].L = and( -524289UL, (2,$_StackDv_P10)[0].L )
  244.                   (2,$_StackDv_P10)[0].L = and( -4293918721UL, (2,$_StackDv_P10)[0].L )
  244.                   (2,$_StackDv_P10)[0].L = and( 0xffffff00ffffffffUL, (2,$_StackDv_P10)[0].L )
  244.                   (2,$_StackDv_P10)[0].L = and( 0xffff00ffffffffffUL, (2,$_StackDv_P10)[0].L )
  244.                   (2,$_StackDv_P10)[0].L = and( 0xff00ffffffffffffUL, (2,$_StackDv_P10)[0].L )
  244.                   (2,$_StackDv_P10)[0].L = or( 0x100000000000000UL, notand( 0xff00000000000000UL, (2,$_StackDv_P10)[0].L ) )
  244.                   (6,$_StackDv_P10)[0] = 0
  244.                   (7,$_StackDv_P10)[0] = 131074
  244.                   (4,$_StackDv_P10)[0].L = int( $LCS_IOitem_162, 8 )
  244.                   (5,$_StackDv_P10)[0].L = 32
  244.                   (6,$_StackDv_P10)[0].L = 1
  244.                   (7,$_StackDv_P10)[0].L = 2
  244.                   (8,$_StackDv_P10)[0].L = 1
  244.                   $_StackIolist_O23 = $_StaticIolist_O22
  244.                   (2,$_StackIolist_O23)[0].L = int( loc( $_StackDv_P10 ), 8 )
  244.                   _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $_StackIolist_O23[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  244.                   if ( $MR_kmax_12 > 0 ) then
  244.                      $I_L244_S301 = 0
  244.                      $SR_S303 = $I_L242_S296
  244.                      $LIS_E102 = int( pointer to c_union Pointer_union( loc( (3,$_StackIolist_O26)[0].L ) ), 8 )
  244.                      $LCS_IL242_163 = 1 + $I_L242_S296
  244.                      $LIS_S194 = $LCS_IL242_163 <= 0
  244.                      do
  244.                         if ( int( $LIS_S194 .or. $LCS_IL242_163 > t$3 ) /= 0 ) then
  244.                            substr[t$67,0:16] = 'Prec_LrgScl.f90'
  244.                            substr[t$68,0:4] = 'T'
  244.                            t$69 = $LCS_IL242_163
  244.                            $Con_P105 = 244
  244.                            $Con_P106 = 1
  244.                            $Con_P107 = 1
  244.                            call _bounds_error( substr[t$67,0:16], $Con_P105, substr[t$68,0:2], $Con_P106, $Con_P107, t$3, t$69, t$66 )
  244.                         endif
  244.                         $LCS_IL244_164 = 1 + $I_L244_S301
  244.                         if ( int( $LCS_IL244_164 <= 0 .or. $LCS_IL244_164 > t$4 ) /= 0 ) then
  244.                            substr[t$71,0:16] = 'Prec_LrgScl.f90'
  244.                            substr[t$72,0:4] = 'T'
  244.                            t$73 = $LCS_IL244_164
  244.                            $Con_P105 = 244
  244.                            $Con_P106 = 2
  244.                            $Con_P107 = 1
  244.                            call _bounds_error( substr[t$71,0:16], $Con_P105, substr[t$72,0:2], $Con_P106, $Con_P107, t$4, t$73, t$70 )
  244.                         endif
  244.                         $nfprt_S302 = nfprt
  244.                         $Unit_temp_O2 = $nfprt_S302
  244.                         $IOitem_O13 = 0[t$40,$SR_S303].L
  244.                         $_StackCntrl_O18 = $_StaticCntrl_O24
  244.                         $MR_StackCntrl_S304 = loc( $Unit_temp_O2 )
  244.                         (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S304
  244.                         $_StackIolist_O26 = $_StaticIolist_O25
  244.                         0[$LIS_E102,0].L = loc( $IOitem_O13 )
  244.                         _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $_StackIolist_O26[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  244.                         $SR_S303 = $LCS_MR_ncols_161 + $SR_S303
  244.                         $I_L244_S301 = 1 + $I_L244_S301
  244.                         if ( $I_L244_S301 >= $LIS_S198 ) exit
  244.                      enddo
  244.                   endif
  244.                   $nfprt_S305 = nfprt
  244.                   $Unit_temp_O3 = $nfprt_S305
  244.                   $_StackCntrl_O18 = $_StaticCntrl_O27
  244.                   $MR_StackCntrl_S306 = loc( $Unit_temp_O3 )
  244.                   (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S306
  244.                   _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $StaticIolist_O28[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  245.                   $nfprt_S307 = nfprt
  245.                   $Unit_temp_O4 = $nfprt_S307
  245.                   $_StackCntrl_O18 = $_StaticCntrl_O29
  245.                   $MR_StackCntrl_S308 = loc( $Unit_temp_O4 )
  245.                   (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S308
  245.                   _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $StaticIolist_O30[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  245.                   if ( $MR_kmax_12 > 0 ) then
  245.                      $I_L245_S309 = 0
  245.                      $SR_S311 = $I_L242_S296
  245.                      $LIS_E103 = int( pointer to c_union Pointer_union( loc( (3,$_StackIolist_O33)[0].L ) ), 8 )
  245.                      $LCS_IL242_165 = 1 + $I_L242_S296
  245.                      $LIS_S200 = $LCS_IL242_165 <= 0
  245.                      do
  245.                         if ( int( $LIS_S200 .or. $LCS_IL242_165 > t$3 ) /= 0 ) then
  245.                            substr[t$78,0:16] = 'Prec_LrgScl.f90'
  245.                            substr[t$79,0:4] = 'TF'
  245.                            t$69 = $LCS_IL242_165
  245.                            $Con_P105 = 245
  245.                            $Con_P106 = 1
  245.                            $Con_P107 = 1
  245.                            call _bounds_error( substr[t$78,0:16], $Con_P105, substr[t$79,0:3], $Con_P106, $Con_P107, t$3, t$69, t$77 )
  245.                         endif
  245.                         $LCS_IL245_166 = 1 + $I_L245_S309
  245.                         if ( int( $LCS_IL245_166 <= 0 .or. $LCS_IL245_166 > t$4 ) /= 0 ) then
  245.                            substr[t$81,0:16] = 'Prec_LrgScl.f90'
  245.                            substr[t$82,0:4] = 'TF'
  245.                            t$73 = $LCS_IL245_166
  245.                            $Con_P105 = 245
  245.                            $Con_P106 = 2
  245.                            $Con_P107 = 1
  245.                            call _bounds_error( substr[t$81,0:16], $Con_P105, substr[t$82,0:3], $Con_P106, $Con_P107, t$4, t$73, t$80 )
  245.                         endif
  245.                         $nfprt_S310 = nfprt
  245.                         $Unit_temp_O5 = $nfprt_S310
  245.                         $IOitem_O14 = 0[$LIS_S202,$SR_S311].L
  245.                         $_StackCntrl_O18 = $_StaticCntrl_O31
  245.                         $MR_StackCntrl_S312 = loc( $Unit_temp_O5 )
  245.                         (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S312
  245.                         $_StackIolist_O33 = $_StaticIolist_O32
  245.                         0[$LIS_E103,0].L = loc( $IOitem_O14 )
  245.                         _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $_StackIolist_O33[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  245.                         $SR_S311 = $LCS_MR_ncols_161 + $SR_S311
  245.                         $I_L245_S309 = 1 + $I_L245_S309
  245.                         if ( $I_L245_S309 >= $LIS_S198 ) exit
  245.                      enddo
  245.                   endif
  245.                   $nfprt_S313 = nfprt
  245.                   $Unit_temp_O6 = $nfprt_S313
  245.                   $_StackCntrl_O18 = $_StaticCntrl_O34
  245.                   $MR_StackCntrl_S314 = loc( $Unit_temp_O6 )
  245.                   (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S314
  245.                   _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $StaticIolist_O35[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  246.                   $nfprt_S315 = nfprt
  246.                   $Unit_temp_O7 = $nfprt_S315
  246.                   $_StackCntrl_O18 = $_StaticCntrl_O36
  246.                   $MR_StackCntrl_S316 = loc( $Unit_temp_O7 )
  246.                   (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S316
  246.                   _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $StaticIolist_O37[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  246.                   if ( $MR_kmax_12 > 0 ) then
  246.                      $I_L246_S317 = 0
  246.                      $SR_S319 = $I_L242_S296
  246.                      $LIS_E104 = int( pointer to c_union Pointer_union( loc( (3,$_StackIolist_O40)[0].L ) ), 8 )
  246.                      $LCS_IL242_167 = 1 + $I_L242_S296
  246.                      $LIS_S205 = $LCS_IL242_167 <= 0
  246.                      do
  246.                         if ( int( $LIS_S205 .or. $LCS_IL242_167 > t$3 ) /= 0 ) then
  246.                            substr[t$87,0:16] = 'Prec_LrgScl.f90'
  246.                            substr[t$88,0:4] = 'Q'
  246.                            t$69 = $LCS_IL242_167
  246.                            $Con_P105 = 246
  246.                            $Con_P106 = 1
  246.                            $Con_P107 = 1
  246.                            call _bounds_error( substr[t$87,0:16], $Con_P105, substr[t$88,0:2], $Con_P106, $Con_P107, t$3, t$69, t$86 )
  246.                         endif
  246.                         $LCS_IL246_168 = 1 + $I_L246_S317
  246.                         if ( int( $LCS_IL246_168 <= 0 .or. $LCS_IL246_168 > t$4 ) /= 0 ) then
  246.                            substr[t$90,0:16] = 'Prec_LrgScl.f90'
  246.                            substr[t$91,0:4] = 'Q'
  246.                            t$73 = $LCS_IL246_168
  246.                            $Con_P105 = 246
  246.                            $Con_P106 = 2
  246.                            $Con_P107 = 1
  246.                            call _bounds_error( substr[t$90,0:16], $Con_P105, substr[t$91,0:2], $Con_P106, $Con_P107, t$4, t$73, t$89 )
  246.                         endif
  246.                         $nfprt_S318 = nfprt
  246.                         $Unit_temp_O8 = $nfprt_S318
  246.                         $IOitem_O15 = 0[t$34,$SR_S319].L
  246.                         $_StackCntrl_O18 = $_StaticCntrl_O38
  246.                         $MR_StackCntrl_S320 = loc( $Unit_temp_O8 )
  246.                         (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S320
  246.                         $_StackIolist_O40 = $_StaticIolist_O39
  246.                         0[$LIS_E104,0].L = loc( $IOitem_O15 )
  246.                         _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $_StackIolist_O40[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  246.                         $SR_S319 = $LCS_MR_ncols_161 + $SR_S319
  246.                         $I_L246_S317 = 1 + $I_L246_S317
  246.                         if ( $I_L246_S317 >= $LIS_S198 ) exit
  246.                      enddo
  246.                   endif
  246.                   $nfprt_S321 = nfprt
  246.                   $Unit_temp_O9 = $nfprt_S321
  246.                   $_StackCntrl_O18 = $_StaticCntrl_O41
  246.                   $MR_StackCntrl_S322 = loc( $Unit_temp_O9 )
  246.                   (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S322
  246.                   _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $StaticIolist_O42[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  247.                   $nfprt_S323 = nfprt
  247.                   $Unit_temp_O10 = $nfprt_S323
  247.                   $_StackCntrl_O18 = $_StaticCntrl_O43
  247.                   $MR_StackCntrl_S324 = loc( $Unit_temp_O10 )
  247.                   (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S324
  247.                   _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $StaticIolist_O44[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  247.                   if ( $MR_kmax_12 > 0 ) then
  247.                      $I_L247_S325 = 0
  247.                      $SR_S327 = $I_L242_S296
  247.                      $LIS_E105 = int( pointer to c_union Pointer_union( loc( (3,$_StackIolist_O47)[0].L ) ), 8 )
  247.                      $LCS_IL242_169 = 1 + $I_L242_S296
  247.                      $LIS_S209 = $LCS_IL242_169 <= 0
  247.                      do
  247.                         if ( int( $LIS_S209 .or. $LCS_IL242_169 > t$3 ) /= 0 ) then
  247.                            substr[t$96,0:16] = 'Prec_LrgScl.f90'
  247.                            substr[t$97,0:4] = 'QF'
  247.                            t$69 = $LCS_IL242_169
  247.                            $Con_P105 = 247
  247.                            $Con_P106 = 1
  247.                            $Con_P107 = 1
  247.                            call _bounds_error( substr[t$96,0:16], $Con_P105, substr[t$97,0:3], $Con_P106, $Con_P107, t$3, t$69, t$95 )
  247.                         endif
  247.                         $LCS_IL247_170 = 1 + $I_L247_S325
  247.                         if ( int( $LCS_IL247_170 <= 0 .or. $LCS_IL247_170 > t$4 ) /= 0 ) then
  247.                            substr[t$99,0:16] = 'Prec_LrgScl.f90'
  247.                            substr[t$100,0:4] = 'QF'
  247.                            t$73 = $LCS_IL247_170
  247.                            $Con_P105 = 247
  247.                            $Con_P106 = 2
  247.                            $Con_P107 = 1
  247.                            call _bounds_error( substr[t$99,0:16], $Con_P105, substr[t$100,0:3], $Con_P106, $Con_P107, t$4, t$73, t$98 )
  247.                         endif
  247.                         $nfprt_S326 = nfprt
  247.                         $Unit_temp_O11 = $nfprt_S326
  247.                         $IOitem_O16 = 0[$LIS_S211,$SR_S327].L
  247.                         $_StackCntrl_O18 = $_StaticCntrl_O45
  247.                         $MR_StackCntrl_S328 = loc( $Unit_temp_O11 )
  247.                         (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S328
  247.                         $_StackIolist_O47 = $_StaticIolist_O46
  247.                         0[$LIS_E105,0].L = loc( $IOitem_O16 )
  247.                         _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $_StackIolist_O47[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  247.                         $SR_S327 = $LCS_MR_ncols_161 + $SR_S327
  247.                         $I_L247_S325 = 1 + $I_L247_S325
  247.                         if ( $I_L247_S325 >= $LIS_S198 ) exit
  247.                      enddo
  247.                   endif
  247.                   $nfprt_S329 = nfprt
  247.                   $Unit_temp_O12 = $nfprt_S329
  247.                   $_StackCntrl_O18 = $_StaticCntrl_O48
  247.                   $MR_StackCntrl_S330 = loc( $Unit_temp_O12 )
  247.                   (1,$_StackCntrl_O18)[0].L = $MR_StackCntrl_S330
  247.                   _fwf( pointer to integer (kind=8)( loc( $_StackCntrl_O18 ) ), pointer to integer (kind=8)( loc( $StaticIolist_O49[0].L ) ), pointer to integer (kind=8)( loc( $_IO_Lib_Stack_O20 ) ) )
  247.                endif
  249.                $I_L242_S296 = 1 + $I_L242_S296
  248.                if ( $I_L242_S296 >= $LCS_MR_ncols_161 ) exit
  248.             enddo
  248.          endif
  248.       endif
  253.       if ( $MR_ncols_11 > 0 ) then
  253.          $I_L253_S333 = 0
  253.          $LCS_171 = $MR_ncols_11
  253.          if ( $LCS_171 >= 2 ) then !  99.50%
  253.             $TC_29 = and( -2, $LCS_171 )
  253.             $LC_S331 = -$TC_29
  253.             $SI_S332 = 0
  254.             $LIS_107[0:2:1].L = _bcst( 5.0e-1, 2 )
  254.             $LIS_E106 = loc( geshem )
  253.             if ( $LC_S331 < -7 ) then
  253.                do
  254.                   $LCS_172 = $LIS_E106 + $SI_S332
  254.                   $LCS_173 = t$31 + $SI_S332
  254.                   0[$LCS_172:2:1].L = $LIS_107[0:2:1].L * 0[$LCS_173:2:1].L + 0[$LCS_172:2:1].L
  254.                   2[$LCS_172:2:1].L = $LIS_107[0:2:1].L * 2[$LCS_173:2:1].L + 2[$LCS_172:2:1].L
  254.                   4[$LCS_172:2:1].L = $LIS_107[0:2:1].L * 4[$LCS_173:2:1].L + 4[$LCS_172:2:1].L
  254.                   6[$LCS_172:2:1].L = $LIS_107[0:2:1].L * 6[$LCS_173:2:1].L + 6[$LCS_172:2:1].L
  253.                   $SI_S332 = 64 + $SI_S332
  253.                   $LC_S331 = 8 + $LC_S331
  253.                   if ( $LC_S331 >= -7 ) exit
  253.                enddo
  253.             endif
  253.             if ( $LC_S331 < 0 ) then
  253.                do
  254.                   $LCS_174 = $LIS_E106 + $SI_S332
  254.                   0[$LCS_174:2:1].L = $LIS_107[0:2:1].L * 0[t$31 + $SI_S332:2:1].L + 0[$LCS_174:2:1].L
  253.                   $SI_S332 = 16 + $SI_S332
  253.                   $LC_S331 = 2 + $LC_S331
  253.                   if ( $LC_S331 >= 0 ) exit
  253.                enddo
  253.             endif
  253.             $I_L253_S333 = $TC_29
  253.          endif
  253.          if ( $MR_ncols_11 > $I_L253_S333 ) then !  99.50%
  254.             $MR_prec_103 = 0[t$31,$I_L253_S333].L
  254.             $LCS_geshem_175 = loc( geshem )
  254.             $MR_geshem_S334 = 0[$LCS_geshem_175,$I_L253_S333].L
  254.             $MR_geshem_S335 = $MR_geshem_S334 + 5.0e-1 * $MR_prec_103
  254.             0[$LCS_geshem_175,$I_L253_S333].L = $MR_geshem_S335
  254.          endif
  254.       endif
   59.       _free( t$18 )
  260.       return
  260.       end
  260.       
    6.       
    6.       module lrgsclprec
  263.       return
  263.       end
  263.       
