      SUBROUTINE POLAVG(FIELD,LONS,LATS)
C
C     SUBROUTINE TO AVERAGE POLE AREAS FOR TYPE 2 (POLE CENTERED)
C     GRIDS.
C
C     ARGUMENTS
C     FIELD    ARRAY TO BE AVERAGED AT POLES
C     LONS     NUMBER OF LONGITUDE POINTS
C     LATS     NUMBER OF LATITUDE POINTS
      DIMENSION FIELD(LONS,LATS)
      TOT1 = 0.0
      TOT2 = 0.0
      DO 1000 I = 1 , LONS
      TOT1 = TOT1 + FIELD(I,1)
      TOT2 = TOT2 + FIELD(I,LATS)
 1000 CONTINUE
      TOT1 = TOT1 / FLOAT(LONS)
      TOT2 = TOT2 / FLOAT(LONS)
      DO 2000 I = 1 , LONS
      FIELD(I,1) = TOT1
      FIELD(I,LATS) = TOT2
 2000 CONTINUE
      RETURN
      END
