      SUBROUTINE FIXSL(LONOUT,LATOUT,SMSK,MASK,I,J,
     *                 K1,K2,K3,K4,K5,K6,K7,K8)
C
      INTEGER SMSK(LONOUT,LATOUT)
      INTEGER*2 MASK(LONOUT,LATOUT)
C
      WRITE(6,500)I,J,K1,K2,K3,K4,SMSK(I,J),K5,K6,K7,K8
  500 FORMAT(' AT LAND POINT VALUE UNDEFINED AT I,J=',2I4/
     *' WITH NO UNAMBIGOUS NEARBY VALUES.  LOCAL AREA:'/
     *(' ',10X,3I3))
C
      IF (MASK(I,J) .EQ. 1) THEN
      MASK(I,J)=0
      WRITE(6,*)' SEA-LAND MASK CHANGED FROM 1 TO 0'
      ELSE
      MASK(I,J)=1
      WRITE(6,*)' SEA-LAND MASK CHANGED FROM 0 TO 1'
      ENDIF
C
      RETURN
      END
