#!/bin/ksh
#help#
#************************************************************************************#
#                                                                                    #
# script to run CPTEC OPERATION                                                      #
# EnvironmentalVariablesMCGA.ksh    TQZZZZLXXX                                       #
#                                                                                    #
#                    ZZZZ   => 4 digits spectral resolution                          #
#                     XXX   => 3 digits vertical resolution                          #
#                                                                                    #
#************************************************************************************#
#help#

#
# Caminhos
#

# Caminho do BAM no HOME
export HOMEBASE=/scratchin/grupos/assim_dados/home/${USER}/SMG/cptec/bam

# Caminho do BAM no scratchin (SUBMIT_HOME)
export SUBTBASE=/scratchin/grupos/assim_dados/home/${USER}/SMG/datainout/bam

# Caminho do BAM no scratchout (SUBMIT_WORK)
export WORKBASE=/scratchout/grupos/assim_dados/home/${USER}/SMG/datainout/bam

#
# Utilitarios
#

export caldate=${HOMEBASE}/utils/bin/caldate.3.0.1
export DIRGRADS=/opt/grads/2.0.a9/bin

#
# Variáveis do PBS
#

export QUOTA=CPTEC
export PBS_TUPA=eslogin13
export PBS_AUX=aux20-eth4
export HSTMAQ=$(uname -n)
export MAQUI=$(uname -s)


export tmstp=$(date +'%s')

