PROGRAM PLATLON
!SUBROUTINE PLATLON(LONI,LONF,LATI,LATF,IM,JM,PLONI,PLONF,PLATI,PLATF,NPLON,NPLAT)

IMPLICIT NONE

REAL  :: LONI,LONF,LATI,LATF
INTEGER :: IM,JM
INTEGER :: PLONI,PLONF,PLATI,PLATF,NPLAT,NPLON

REAL :: ALONI,ALONF,ALATI,ALATF,DELTAG,PLAT,PLON,DIF
INTEGER :: VPROV

IM=192
JM=96
LONI=258.75
LONF=348.75
LATI=-60.0
LATF=15.0

IF (LATI >= LATF .OR. LONI >= LONF)THEN
STOP 'ERROR: LATI >= LATF OU LONI >= LONF'
ENDIF
IF (LONI < 0.0 .OR. LONF < 0.0)THEN
STOP 'ERROR: LONI and LONF can not be less than 0.0. Must be 0 to 360'
ENDIF

ALATI=LATI
ALATF=LATF
ALONI=LONI
ALONF=LONF

DELTAG=180.0/JM

PLAT=ALATI/DELTAG
PLATI=IFIX(PLAT)
DIF=ABS(PLAT-FLOAT(PLATI))
IF (DIF .GE. 0.5) THEN
IF (PLATI > 0) PLATI=PLATI+1
IF (PLATI < 0) PLATI=PLATI-1
ENDIF
IF (PLATI == 0 .AND. LATF > 0.0) THEN
PLATI=1
ENDIF
IF (PLATI > 0) THEN
PLATI=(JM/2)-PLATI+1
ELSE
PLATI=(JM/2)-PLATI
ENDIF
PLAT=ALATF/DELTAG
PLATF=IFIX(PLAT)
DIF=ABS(PLAT-FLOAT(PLATF))
IF (DIF .GE. 0.5) THEN
IF (PLATF > 0) PLATF=PLATF+1
IF (PLATF < 0) PLATF=PLATF-1
ENDIF
IF (PLATF == 0 .AND. LATI < 0.0) THEN
PLATI=-1
ENDIF
IF (PLATF > 0) THEN
PLATF=(JM/2)-PLATF+1
ELSE
PLATF=(JM/2)-PLATF
ENDIF
NPLAT=ABS(PLATF-PLATI)+1
VPROV=PLATI
PLATI=PLATF
PLATF=VPROV

PLON=ALONI/DELTAG
PLONI=IFIX(PLON)
DIF=PLON-FLOAT(PLONI)
IF (DIF .GE. 0.5) THEN
PLONI=PLONI+1
ENDIF
IF (PLONI .EQ. 0) PLONI=1
PLON=ALONF/DELTAG
PLONF=IFIX(PLON)
DIF=PLON-FLOAT(PLONF)
IF (DIF .GE. 0.5) THEN
PLONF=PLONF+1
ENDIF
NPLON=ABS(PLONF-PLONI)+1

write(*,*)'PLONI=',PLONI
write(*,*)'PLONF=',PLONF
write(*,*)'PLATI=',PLATI
write(*,*)'PLATF=',PLATF
write(*,*)'NPLAT=',NPLAT
write(*,*)'NPLON=',NPLON

END

