PROGRAM PROV

IMPLICIT NONE

INTEGER :: I,J,K,L,M,ICL,IAN,FAN,IFC,FFC
INTEGER :: ierr,MEMBM
INTEGER :: PREC,AREC,CREC,NIVEL
INTEGER :: NP,NMEMBROS,IM,JM
INTEGER :: PLONI,PLONF,PLATI,PLATF,NPLON,NPLAT

REAL :: LIMIAR,AREA
REAL :: HNLATI,HNLATF,HNLONI,HNLONF
REAL :: HSLATI,HSLATF,HSLONI,HSLONF
REAL :: TRLATI,TRLATF,TRLONI,TRLONF
REAL :: ASLATI,ASLATF,ASLONI,ASLONF
REAL, DIMENSION(:),       ALLOCATABLE  :: PMRD,BRIERHN,BRIERHS,BRIERTR,BRIERAS
REAL, DIMENSION(:,:),     ALLOCATABLE  :: DATAA,DATAC,ANDATAA,OBSV
REAL, DIMENSION(:,:,:),   ALLOCATABLE  :: PROB
REAL, DIMENSION(:,:,:,:), ALLOCATABLE  :: DATAP,ANDATAP

CHARACTER(LEN= 10) :: DATEY
CHARACTER(LEN= 22) :: DIRARQ
CHARACTER(LEN=100) :: NAMEA,NAMEC
CHARACTER(LEN= 10), DIMENSION(:),   ALLOCATABLE :: ARQUI
CHARACTER(LEN= 12), DIMENSION(:),   ALLOCATABLE :: IPREV
CHARACTER(LEN=100), DIMENSION(:,:), ALLOCATABLE :: NAMEP

LOGICAL :: EXARQ

DIRARQ='/rede/ENS/NMC/T062L28/'

!
!OBTEM PARAMETROS NECESSARIOS
!

NAMELIST /RECORDS/ PREC,AREC,CREC,NIVEL
NAMELIST /LIMR/    LIMIAR
NAMELIST /PARAM/   NP,NMEMBROS,IM,JM
NAMELIST /LATLON/  HNLATI,HNLATF,HNLONI,HNLONF, &
                   HSLATI,HSLATF,HSLONI,HSLONF, &
                   TRLATI,TRLATF,TRLONI,TRLONF, &
                   ASLATI,ASLATF,ASLONI,ASLONF 
                  
OPEN(1,FILE='recs.nml',STATUS='OLD')
READ(1,nml=RECORDS)
CLOSE(1)
OPEN(2,FILE='limiar.nml',STATUS='OLD')
READ(2,nml=LIMR)
CLOSE(2)
OPEN(3,FILE=' param.nml',STATUS='OLD')
READ(3,nml=PARAM)
CLOSE(3)
OPEN(4,FILE=' latlon.nml',STATUS='OLD')
READ(4,nml=LATLON)
CLOSE(4)

CALL GETARG(1,DATEY)

!
!FAZ ALOCACAO DINAMICA DAS VARIAVEIS
!

ALLOCATE(ARQUI(NMEMBROS), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: ARQUI'
ALLOCATE(NAMEP(NMEMBROS,NP), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: NAMEP'
ALLOCATE(DATAC(IM,JM), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: DATAC'
ALLOCATE(DATAA(IM,JM), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: DATAA'
ALLOCATE(ANDATAA(IM,JM), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: ANDATAA'
ALLOCATE(DATAP(NMEMBROS,NP,IM,JM), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: DATAP'
ALLOCATE(ANDATAP(NMEMBROS,NP,IM,JM), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: ANDATAP'
ALLOCATE(PROB(NP,IM,JM), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: PROB'
ALLOCATE(OBSV(IM,JM), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: OBSV'
ALLOCATE(PMRD(JM), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: PMRD'
ALLOCATE(BRIERHN(NP), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: BRIERHN'
ALLOCATE(BRIERHS(NP), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: BRIERHS'
ALLOCATE(BRIERTR(NP), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: BRIERTR'
ALLOCATE(BRIERAS(NP), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: BRIERAS'
ALLOCATE(IPREV(NP), STAT=ierr)
IF (ierr .NE. 0) STOP 'NAO ALOCOU CORRETAMENTE: IPREV'

!
!OBTEM O NOME DOS ARQUIVOS DE: CLIMATOLOGIA, ANALISE E PREVISOES
!

!CLIMATOLOGIA
OPEN(5,FILE='filec.nml',STATUS='OLD')
READ(5,'(A)') NAMEC
CLOSE(5)
ICL=INDEX(NAMEC,' ')-1
WRITE(*,*)'NAMEC=',NAMEC(1:ICL)

!ANALISE
OPEN(6,FILE='fileanl',STATUS='OLD')
READ(6,'(A)') NAMEA
CLOSE(6)
IAN=INDEX(NAMEA,'GPOS')
FAN=INDEX(NAMEA,' ')-1
NAMEA=DIRARQ//NAMEA(IAN:FAN-4)
IAN=INDEX(NAMEA,' ')-1
WRITE(*,*)'NAMEA=',NAMEA(1:IAN)

!PREVISOES
MEMBM=(NMEMBROS-1)/2
DO K=1,MEMBM
ARQUI(K)(1:7)='filefct'
WRITE(ARQUI(K)(8:9),'(I2.2)') K
ARQUI(K)(10:10)='P'
WRITE(*,*)'ARQUI=',ARQUI(K)
OPEN(7,FILE=ARQUI(K),STATUS='OLD')
DO L=1,NP
READ(7,'(A)') NAMEP(K,L)
IFC=INDEX(NAMEP(K,L),'GPOS')
FFC=INDEX(NAMEP(K,L),' ')-1
NAMEP(K,L)=DIRARQ//NAMEP(K,L)(IFC:FFC-4)
IFC=INDEX(NAMEP(K,L),' ')-1
WRITE(*,*)'NAMEP=',NAMEP(K,L)(1:IFC)
ENDDO
CLOSE(7)
ENDDO
DO K=1,MEMBM
ARQUI(K+MEMBM)(1:7)='filefct'
WRITE(ARQUI(K+MEMBM)(8:9),'(I2.2)') K
ARQUI(K+MEMBM)(10:10)='N'
WRITE(*,*)'ARQUI=',ARQUI(K+MEMBM)
OPEN(7,FILE=ARQUI(K+MEMBM),STATUS='OLD')
DO L=1,NP
READ(7,'(A)') NAMEP(K+MEMBM,L)
IFC=INDEX(NAMEP(K+MEMBM,L),'GPOS')
FFC=INDEX(NAMEP(K+MEMBM,L),' ')-1
NAMEP(K+MEMBM,L)=DIRARQ//NAMEP(K+MEMBM,L)(IFC:FFC-4)
IFC=INDEX(NAMEP(K+MEMBM,L),' ')-1
WRITE(*,*)'NAMEP=',NAMEP(K+MEMBM,L)(1:IFC)
ENDDO
CLOSE(7)
ENDDO
ARQUI(NMEMBROS)(1:10)='filefctNMC'
WRITE(*,*)'ARQUI=',ARQUI(NMEMBROS)
OPEN(7,FILE=ARQUI(NMEMBROS),STATUS='OLD')
DO L=1,NP
READ(7,'(A)') NAMEP(NMEMBROS,L)
IFC=INDEX(NAMEP(NMEMBROS,L),'GPOS')
FFC=INDEX(NAMEP(NMEMBROS,L),' ')-1
NAMEP(NMEMBROS,L)=DIRARQ//NAMEP(NMEMBROS,L)(IFC:FFC-4)
IFC=INDEX(NAMEP(NMEMBROS,L),' ')-1
WRITE(*,*)'NAMEP=',NAMEP(NMEMBROS,L)(1:IFC)
ENDDO
CLOSE(7)

WRITE(*,*)' '
!
!FAZ A LEITURA DOS DADOS DE CLIMATOLOGIA, ANALISE E PREVISOES
!

!CLIMATOLOGIA
INQUIRE(FILE=NAMEC,EXIST=EXARQ)
IF (EXARQ) THEN
WRITE(*,*)'LENDO: ',NAMEC
OPEN(50,FILE=NAMEC,ACCESS='DIRECT',RECL=IM*JM,FORM='UNFORMATTED',STATUS='OLD',CONVERT='BIG_ENDIAN')
READ(50,REC=CREC) DATAC
CLOSE(50)
ELSE
STOP 'O ARQUIVO DE CLIMATOLOGIA NAO EXISTE'
ENDIF


!ANALISE
INQUIRE(FILE=NAMEA,EXIST=EXARQ)
IF (EXARQ) THEN
WRITE(*,*)'LENDO: ',NAMEA(1:IAN)
OPEN(60,FILE=NAMEA,FORM='UNFORMATTED',STATUS='OLD',CONVERT='BIG_ENDIAN')
DO M=1,AREC
READ(60) DATAA
ENDDO
CLOSE(60)
ELSE
STOP 'O ARQUIVO DE ANALISE NAO EXISTE'
ENDIF

!PREVISOES
DO K=1,NMEMBROS 
DO L=1,NP
INQUIRE(FILE=NAMEP(K,L)(1:IFC),EXIST=EXARQ)
IF (EXARQ) THEN
WRITE(*,*)' '
WRITE(*,*)'LENDO: ',NAMEP(K,L)(1:IFC)
OPEN(70,FILE=NAMEP(K,L)(1:IFC),FORM='UNFORMATTED',STATUS='OLD',CONVERT='BIG_ENDIAN')
DO M=1,PREC
READ(70) DATAP(K,L,1:IM,1:JM)
ENDDO
CLOSE(70)
ELSE
WRITE(*,*)'O ARQUIVO DE PREVISAO NAO EXISTE: ',NAMEP(K,L)(1:IFC)
DATAP(K,L,1:IM,1:JM)=-999.9
ENDIF
ENDDO
ENDDO

!
!CALCULA ANOMALIAS E PROBABILIDADES PREVISTA DE OCORRENCIA DO EVENTO 
!

PROB=0.0
OBSV=0.0

!ANOMALIAS DA ANALISE
ANDATAA=DATAA-DATAC


!ANALISE: (1.0 SE O EVENTO OCORRE) OU (0.0 SE O EVENTO NAO OCORRE)
WHERE (ANDATAA >= LIMIAR)
       OBSV(:,:)=1.0
ENDWHERE       
WHERE (ANDATAA <= -LIMIAR)
       OBSV(:,:)=1.0
ENDWHERE       

!ANOMALIAS DAS PREVISOES E PROBABILIDADES PREVISTA 
DO L=1,NP
DO K=1,NMEMBROS 
WHERE (DATAP(K,L,1:IM,1:JM) /= -999.9)
ANDATAP(K,L,1:IM,1:JM)=DATAP(K,L,1:IM,1:JM)-DATAC(1:IM,1:JM)
ELSEWHERE
ANDATAP(K,L,1:IM,1:JM)= -999.9
ENDWHERE       
WHERE ( (ANDATAP(K,L,1:IM,1:JM) >= LIMIAR) )
       PROB(L,:,:)=PROB(L,:,:)+1.0
ENDWHERE 
WHERE ( (ANDATAP(K,L,1:IM,1:JM) <= -LIMIAR) )
       PROB(L,:,:)=PROB(L,:,:)+1.0
ENDWHERE       
WHERE ( (ANDATAP(K,L,1:IM,1:JM) == -999.9) )
       PROB(L,:,:)=-999.9      
ENDWHERE       
ENDDO
WHERE ( (ANDATAP(K-1,L,1:IM,1:JM) /= -999.9) )
PROB(L,:,:)=PROB(L,:,:)/FLOAT(NMEMBROS)
ENDWHERE       
ENDDO

!
!CALCULA O BRIER SCORE PARA CADA REGIAO E ESCREVE EM ARQUIVO
!

!ABRE O ARQUIVO DE SAIDA DOS INDICES E ESCREVE O CABECALHO
CALL EWRITE(DATEY,NP,IPREV)

!CALCULA OS PESOS MERIDIONAIS
CALL PESOS(JM,PMRD)

!HEMISFERIO NORTE
WRITE(100,1000)'Northern Hemisphere: Lon: ',HNLONI,' to ',HNLONF,'  Lat: ',HNLATI,' to ',HNLATF,'  Level: ',NIVEL,' hPa'
WRITE(100,'(A)')'BRIER SCORE    FCT DAYS  INITIAL DATE'
CALL PLATLON(HNLONI,HNLONF,HNLATI,HNLATF,IM,JM,PLONI,PLONF,PLATI,PLATF,NPLON,NPLAT)
DO L=1,NP 
AREA=0.0
BRIERHN(L)=0.0
DO J=PLATI,PLATF
DO I=PLONI,PLONF
IF (PROB(L,I,J) /= -999.9) THEN
BRIERHN(L)=BRIERHN(L)+PMRD(J)*(PROB(L,I,J)-OBSV(I,J))**2
ELSE
BRIERHN(L)=-99.9
ENDIF
ENDDO
AREA=AREA+PMRD(J)*NPLON
ENDDO
IF (BRIERHN(L) /= -99.9) THEN
BRIERHN(L)=BRIERHN(L)/AREA
ELSE
BRIERHN(L)=-99.9
ENDIF
WRITE(100,1100)BRIERHN(L),NP-L+1,IPREV(NP-L+1)
WRITE(*,*)'AREA HEMISFERIO NORTE: ',AREA
ENDDO

!HEMISFERIO SUL
WRITE(100,'(A10)')'  '
WRITE(100,1000)'Southern Hemisphere: Lon: ',HSLONI,' to ',HSLONF,'  Lat: ',HSLATI,' to ',HSLATF,'  Level: ',NIVEL,' hPa'
WRITE(100,'(A)')'BRIER SCORE    FCT DAYS  INITIAL DATE'
CALL PLATLON(HSLONI,HSLONF,HSLATI,HSLATF,IM,JM,PLONI,PLONF,PLATI,PLATF,NPLON,NPLAT)
DO L=1,NP 
AREA=0.0
BRIERHS(L)=0.0
DO J=PLATI,PLATF
DO I=PLONI,PLONF
IF (PROB(L,I,J) /= -999.9) THEN
BRIERHS(L)=BRIERHS(L)+PMRD(J)*(PROB(L,I,J)-OBSV(I,J))**2
ELSE
BRIERHS(L)=-99.9
ENDIF
ENDDO
AREA=AREA+PMRD(J)*NPLON
ENDDO
IF (BRIERHS(L) /= -99.9) THEN
BRIERHS(L)=BRIERHS(L)/AREA
ELSE
BRIERHS(L)=-99.9
ENDIF
WRITE(100,1100)BRIERHS(L),NP-L+1,IPREV(NP-L+1)
WRITE(*,*)'AREA HEMISFERIO SUL: ',AREA
ENDDO

!TROPICAL
WRITE(100,'(A10)')'  '
WRITE(100,1000)'Tropical Region:     Lon: ',TRLONI,' to ',TRLONF,'  Lat: ',TRLATI,' to ',TRLATF,'  Level: ',NIVEL,' hPa'
WRITE(100,'(A)')'BRIER SCORE    FCT DAYS  INITIAL DATE'
CALL PLATLON(TRLONI,TRLONF,TRLATI,TRLATF,IM,JM,PLONI,PLONF,PLATI,PLATF,NPLON,NPLAT)
DO L=1,NP 
AREA=0.0
BRIERTR(L)=0.0
DO J=PLATI,PLATF
DO I=PLONI,PLONF
IF (PROB(L,I,J) /= -999.9) THEN
BRIERTR(L)=BRIERTR(L)+PMRD(J)*(PROB(L,I,J)-OBSV(I,J))**2
ELSE
BRIERTR(L)=-99.9
ENDIF
ENDDO
AREA=AREA+PMRD(J)*NPLON
ENDDO
IF (BRIERTR(L) /= -99.9) THEN
BRIERTR(L)=BRIERTR(L)/AREA
ELSE
BRIERTR(L)=-99.9
ENDIF
WRITE(100,1100)BRIERTR(L),NP-L+1,IPREV(NP-L+1)
WRITE(*,*)'AREA TROPICAL: ',AREA
ENDDO

!AMERICA DO SUL
WRITE(100,'(A10)')'  '
WRITE(100,1000)'South America:       Lon: ',ASLONI,' to ',ASLONF,'  Lat: ',ASLATI,' to ',ASLATF,'  Level: ',NIVEL,' hPa'
WRITE(100,'(A)')'BRIER SCORE    FCT DAYS  INITIAL DATE'
CALL PLATLON(ASLONI,ASLONF,ASLATI,ASLATF,IM,JM,PLONI,PLONF,PLATI,PLATF,NPLON,NPLAT)
DO L=1,NP 
AREA=0.0
BRIERAS(L)=0.0
DO J=PLATI,PLATF
DO I=PLONI,PLONF
IF (PROB(L,I,J) /= -999.9) THEN
BRIERAS(L)=BRIERAS(L)+PMRD(J)*(PROB(L,I,J)-OBSV(I,J))**2
ELSE
BRIERAS(L)=-99.9
ENDIF
ENDDO
AREA=AREA+PMRD(J)*NPLON
ENDDO
IF (BRIERAS(L) /= -99.9) THEN
BRIERAS(L)=BRIERAS(L)/AREA
ELSE
BRIERAS(L)=-99.9
ENDIF
WRITE(100,1100)BRIERAS(L),NP-L+1,IPREV(NP-L+1)
WRITE(*,*)'AREA AMERICA DO SUL: ',AREA
ENDDO

WRITE(100,'(A)')'   '
WRITE(100,'(A)')' -99.9 means that data are unavailable'

CLOSE(100)

1000 FORMAT(A26,F7.2,A4,F7.2,A7,F6.2,A4,F6.2,A9,I4,A4)
1100 FORMAT(X,F8.4,9X,I2.2,5X,A12)

END

!
!INICIO DAS SUBROTINAS
!
!*******************************PLATLON*****************************
!
SUBROUTINE PLATLON(LONI,LONF,LATI,LATF,IM,JM,PLONI,PLONF,PLATI,PLATF,NPLON,NPLAT)

IMPLICIT NONE

REAL,    INTENT(IN)  :: LONI,LONF,LATI,LATF
INTEGER, INTENT(IN)  :: IM,JM
INTEGER, INTENT(OUT) :: PLONI,PLONF,PLATI,PLATF,NPLAT,NPLON

REAL :: ALONI,ALONF,ALATI,ALATF,DELTAG,PLAT,PLON,DIF
INTEGER :: VPROV

IF (LATI >= LATF .OR. LONI >= LONF)THEN
STOP 'ERROR: LATI >= LATF OU LONI >= LONF'
ENDIF
IF (LONI < 0.0 .OR. LONF < 0.0)THEN
STOP 'ERROR: LONI and LONF can not be less than 0.0. Must be 0 to 360'
ENDIF

ALATI=LATI
ALATF=LATF
ALONI=LONI
ALONF=LONF

DELTAG=180.0/JM

PLAT=ALATI/DELTAG
PLATI=IFIX(PLAT)
DIF=ABS(PLAT-FLOAT(PLATI))
IF (DIF .GE. 0.5) THEN
IF (PLATI > 0) PLATI=PLATI+1
IF (PLATI < 0) PLATI=PLATI-1
ENDIF
IF (PLATI == 0 .AND. LATF > 0.0) THEN
PLATI=1
ENDIF
IF (PLATI > 0) THEN
PLATI=(JM/2)-PLATI+1
ELSE
PLATI=(JM/2)-PLATI
ENDIF
PLAT=ALATF/DELTAG
PLATF=IFIX(PLAT)
DIF=ABS(PLAT-FLOAT(PLATF))
IF (DIF .GE. 0.5) THEN
IF (PLATF > 0) PLATF=PLATF+1
IF (PLATF < 0) PLATF=PLATF-1
ENDIF
IF (PLATF == 0 .AND. LATI < 0.0) THEN
PLATI=-1
ENDIF
IF (PLATF > 0) THEN
PLATF=(JM/2)-PLATF+1
ELSE
PLATF=(JM/2)-PLATF
ENDIF
NPLAT=ABS(PLATF-PLATI)+1
VPROV=PLATI
PLATI=PLATF
PLATF=VPROV

PLON=ALONI/DELTAG
PLONI=IFIX(PLON)
DIF=PLON-FLOAT(PLONI)
IF (DIF .GE. 0.5) THEN
PLONI=PLONI+1
ENDIF
IF (PLONI .EQ. 0) PLONI=1
PLON=ALONF/DELTAG
PLONF=IFIX(PLON)
DIF=PLON-FLOAT(PLONF)
IF (DIF .GE. 0.5) THEN
PLONF=PLONF+1
ENDIF
NPLON=ABS(PLONF-PLONI)+1

write(*,*)'PLONI=',PLONI
write(*,*)'PLONF=',PLONF
write(*,*)'PLATI=',PLATI
write(*,*)'PLATF=',PLATF
write(*,*)'NPLAT=',NPLAT
write(*,*)'NPLON=',NPLON

RETURN
END


!*******************************PESOS*****************************
!
SUBROUTINE PESOS(JM,PMR)

IMPLICIT NONE

INTEGER,             INTENT(IN)  :: JM
REAL, DIMENSION(JM), INTENT(OUT) :: PMR

INTEGER  :: J,ierr
REAL     :: RT,PI,RAD,DELTAG,DELTAR,AREA

PI=4.0*ATAN(1.0)
RT=6.37E6
DELTAG=180.0/FLOAT(JM)

DELTAR=(PI*DELTAG)/180.0

AREA=0.0
RAD=DELTAR/2.0
DO J=0,(JM/2-1)
PMR(JM/2-J)=(RT*RT)*(DELTAR*DELTAR)*COS(RAD)
PMR(JM/2+J+1)=PMR(JM/2-J)
AREA=AREA+(PMR(JM/2-J)+PMR(JM/2+J+1))*192
RAD=RAD+DELTAR
ENDDO

WRITE(*,*)' '
WRITE(*,*)'AREA CALCULADA: ',AREA
WRITE(*,*)'AREA EXATA: ',4*PI*RT**2

RETURN
END


!*******************************EWRITE*****************************
!
SUBROUTINE EWRITE(DATE,NP,DATAP)

IMPLICIT NONE

CHARACTER(LEN=10), INTENT(IN)    :: DATE
INTEGER,           INTENT(IN)    :: NP
CHARACTER(LEN=12), DIMENSION(NP), INTENT(OUT)   :: DATAP

CHARACTER(LEN= 2)                :: MM,DD,HH
CHARACTER(LEN= 4)                :: YY
CHARACTER(LEN=22)                :: DIROUT
CHARACTER(LEN=32)                :: NAMEOUT
CHARACTER(LEN= 3), DIMENSION(12) :: MONS

INTEGER                          :: I,YEARR,MONTH,DATAY,DIF
INTEGER, DIMENSION(12)           :: MONL,MONB

DATA MONL /31,28,31,30,31,30,31,31,30,31,30,31/
DATA MONB /31,29,31,30,31,30,31,31,30,31,30,31/
DATA MONS /'JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'/

DIROUT='/rede/ENS/SKILL/skill/'

YY=DATE(1:4)
MM=DATE(5:6)
DD=DATE(7:8)
HH=DATE(9:10)

READ(YY(1:4),'(I4)') YEARR
READ(MM(1:2),'(I2)') MONTH
READ(DD(1:2),'(I2)') DATAY

NAMEOUT(1:12)='brierscoreg.'
WRITE(NAMEOUT(13:24),'(A2,A,A2,A3,A4)')HH,'Z',DD,MONS(MONTH),YY
NAMEOUT(25:32)='.ens.m01'

WRITE(*,*)'NAMEOUT: ',DIROUT//NAMEOUT

OPEN(100,FILE=DIROUT//NAMEOUT,FORM='FORMATTED',STATUS='UNKNOWN')

WRITE(100,'(A)')'Brier Score of Ensemble Operational CPTEC/COLA T062L28 Spectral Global Model'
WRITE(100,'(A)')'     using as Control Initial Condition NMC T062L28 Spectral Analysis'
WRITE(100,'(A)')'     '
WRITE(100,'(A)')'                  Geopotential Height Anomalies'
WRITE(100,'(A)')'-------------------------------------------------------------------'
WRITE(100,'(A)')'     '
WRITE(100,'(A15,A2,A,A2,A3,A4)')'Analysis Date: ',HH,'Z',DD,MONS(MONTH),YY
WRITE(100,'(A)')'     '

DIF=MOD(YEARR,4)
DO I=1,NP
IF (DIF /= 0) THEN
   DATAY=DATAY-1
   IF (DATAY == 0) THEN
      MONTH=MONTH-1
      IF (MONTH == 0) THEN
         MONTH=12
         YEARR=YEARR-1
      ENDIF
      DATAY=MONL(MONTH)
   ENDIF
ELSE
   DATAY=DATAY-1
   IF (DATAY == 0) THEN
      MONTH=MONTH-1
      IF (MONTH == 0) THEN
         MONTH=12
         YEARR=YEARR-1
      ENDIF
      DATAY=MONB(MONTH)
   ENDIF
ENDIF
WRITE(DATAP(I)(1:12),'(A2,A,I2.2,A3,I4)')HH,'Z',DATAY,MONS(MONTH),YEARR
!WRITE(*,*) 'DATAP(',I,')=',DATAP(I)
ENDDO

RETURN
END





