      SUBROUTINE GL(KHALF,COLRAD)
      INTEGER KHALF
      DOUBLE PRECISION COLRAD(*)
C*
      INTEGER K2,K1,K,ITR
      DOUBLE PRECISION EPS,SI,RK2,SCALE,PI,DRADZ,RAD,DRAD,P1,
     *                 P2,PHI,W,X,SN,DATAN,DSIN,DCOS,DSIGN
C*
      EPS=1.0D-12
      SI=1.0D+00
      K2=2*KHALF
      RK2=DBLE(K2)
      SCALE=2.0D+00/(RK2*RK2)
      K1=K2-1
      PI=DATAN(SI)*4.0D+00
      DRADZ=PI/360.0D+00
      RAD=0.0D+00
C*
      DO 10 K=1,KHALF
      ITR=0
      DRAD=DRADZ
C*
   20 CALL PLY(K2,RAD,P2)
   30 P1=P2
      ITR=ITR+1
      RAD=RAD+DRAD
      CALL PLY(K2,RAD,P2)
      IF (DSIGN(SI,P1) .EQ. DSIGN(SI,P2)) GOTO 30
C*
      IF (DRAD .LT. EPS) GOTO 40
      RAD=RAD-DRAD
      DRAD=DRAD*0.25D+00
      GOTO 20
C*
   40 COLRAD(K)=RAD
      PHI=RAD*180.0D+00/PI
      CALL PLY(K1,RAD,P1)
      X=DCOS(RAD)
      W=SCALE*(1.0D+00-X*X)/(P1*P1)
      SN=DSIN(RAD)
      W=W/(SN*SN)
      CALL PLY(K2,RAD,P1)
   10 CONTINUE
C*
      RETURN
      END
