      SUBROUTINE RECTRG(QF,F)
C*
      INCLUDE "reshsst.h"
C*
      INTEGER IMX,IMXT,JMAXHF
      PARAMETER (IMX=IMAX+2,IMXT=IMAX*3/2+1,JMAXHF=(JMAX+1)/2)
      INTEGER MEND,MEND2,MNWV2,MNWV3,MNWV1
      PARAMETER (MEND=MEND1-1,MEND2=MEND1+1,MNWV2=MEND1*MEND2,
     *          MNWV3=MNWV2+2*MEND1,MNWV1=MNWV3/2)
C*
      REAL QF(MNWV2),F(IMAX,JMAX)
C*
      INTEGER IFAX(13)
      REAL FN(IMX),FS(IMX),GN(IMX),GS(IMX),TRIGS(IMXT)
      INTEGER LA0(MEND1,MEND1),LA1(MEND1,MEND2)
      REAL QLN(MNWV3,JMAXHF),QLNW(MNWV3,JMAXHF),
     *     DCOLRA(JMAXHF),QW(MNWV2,2),GW(IMX)
C*
      COMMON /FFTCMN/ FN,FS,GN,GS,TRIGS,IFAX
      COMMON /PLNCMN/ QLN,DCOLRA,QW,GW,QLNW,LA0,LA1
C*
      INTEGER J,I
C*
      CALL TRANSP(QF,MNWV2,MEND1,MEND1,MEND1,1,LA0,QW,-1)
C*
      DO J=1,JMAXHF
C*
      CALL RESET(FN,IMX)
      CALL RESET(FS,IMX)
C*
      CALL SUMPLN(QF,FN,FS,QLN(1,J),QW)
C*
      CALL FFT991(FN,GN,TRIGS,IFAX,1,IMX,IMAX,1,1)
      CALL FFT991(FS,GS,TRIGS,IFAX,1,IMX,IMAX,1,1)
C*
      DO I=1,IMAX
      F(I,J)=FN(I)
      F(I,JMAX+1-J)=FS(I)
      ENDDO
C*
      ENDDO
C*
      RETURN
      END
