      SUBROUTINE UVTODZ(U,V,QROT,QDIV)
C*
      include "decanl.h"
C*
      INTEGER IMX,IMXT,JMAXHF
      PARAMETER (IMX=IMAX+2,IMXT=IMAX*3/2+1,JMAXHF=JMAX/2)
      INTEGER MEND1,MEND2,MNWV2
      PARAMETER (MEND1=MEND+1,MEND2=MEND1+1,
     *           MNWV2=MEND1*MEND2)
C*
      REAL U(IMAX,JMAX,KMAX),V(IMAX,JMAX,KMAX),
     *     QROT(MNWV2,KMAX),QDIV(MNWV2,KMAX)
C*
      INTEGER J,I,K,MN
      INTEGER IFAX(13)
      REAL UN(IMX,KMAX),US(IMX,KMAX),
     *     VN(IMX,KMAX),VS(IMX,KMAX),
     *     GW(IMX,KMAX),TRIGS(IMXT)
C*
      COMMON /FFTCMN/ TRIGS,IFAX
      COMMON /WKAREA/ UN,US,VN,VS,GW
C*
      CALL RESET(QROT,MNWV2*KMAX)
      CALL RESET(QDIV,MNWV2*KMAX)
C*
      DO J=1,JMAXHF
C*
      DO K=1,KMAX
      DO I=1,IMAX
      UN(I,K)=U(I,J,K)
      US(I,K)=U(I,JMAX+1-J,K)
      VN(I,K)=V(I,J,K)
      VS(I,K)=V(I,JMAX+1-J,K)
      ENDDO
      DO I=IMAX+1,IMX
      UN(I,K)=0.0
      US(I,K)=0.0
      VN(I,K)=0.0
      VS(I,K)=0.0
      ENDDO
      ENDDO
C*
      CALL FFT991(UN,GW,TRIGS,IFAX,1,IMX,IMAX,KMAX,-1)
      CALL FFT991(US,GW,TRIGS,IFAX,1,IMX,IMAX,KMAX,-1)
      CALL FFT991(VN,GW,TRIGS,IFAX,1,IMX,IMAX,KMAX,-1)
      CALL FFT991(VS,GW,TRIGS,IFAX,1,IMX,IMAX,KMAX,-1)
C*
      CALL SYMASY(UN,US,GW,KMAX)
      CALL SYMASY(VN,VS,GW,KMAX)
      CALL MSU22(US,UN,VS,VN,QDIV,J)
      CALL PSU22(US,UN,VS,VN,QROT,J)
C*
      ENDDO
C*
C*    MSU22 COMPUTES CONVERGENCE, SIGNAL OF QDIV MUST BE CHANGED
C*
      DO K=1,KMAX
      DO MN=1,MNWV2
      QDIV(MN,K)=-QDIV(MN,K)
      ENDDO
      ENDDO
C*
      RETURN
      END
