       PROGRAM GETMOD
C*
C*    COMPUTE VERTICAL AND HORIZONTAL MODES
C*
      INCLUDE "resvnmd.h"
C*
      INTEGER NFG,MODS
      REAL GH(KMAX)
      INTEGER MATZ,FIFTY
      REAL TWO,EPS
      DATA MATZ /1/, FIFTY /50/, TWO /2.0E0/
C*
      EPS=TWO**(-FIFTY)
C*
      WRITE(*,'(/,A25,1PG12.5,/)')' NORMAL MODE PRECISION = ',EPS
C*
      NFG=80
      OPEN(NFG,FORM='UNFORMATTED',STATUS='UNKNOWN')
C*
      CALL VERMOD(NFG,GH,EPS,MATZ)
C*
      MODS=6
      CALL HORMOD(NFG,GH,MODS,EPS)
C*
      CLOSE(NFG)
C*
      STOP
      END
