      SUBROUTINE RECTRG(QF,F,MNWVD,KDIM)
C*
#include <recanl.h>
C*
      INTEGER IMX,IMXT,JMAXHF
      PARAMETER (IMX=IMAX+2,IMXT=IMAX*3/2+1,JMAXHF=JMAX/2)
      INTEGER MEND1,MEND2,MNWV2,MNWV3,MNWV1
      PARAMETER (MEND1=MEND+1,MEND2=MEND1+1,MNWV2=MEND1*MEND2,
     *          MNWV3=MNWV2+2*MEND1,MNWV1=MNWV3/2)
C*
      INTEGER MNWVD,KDIM
      REAL QF(MNWVD,KDIM),F(IMAX,JMAX,KDIM)
C*
      INTEGER ISCVC
      INTEGER IFAX(13)
      REAL FN(IMX,KMAX),FS(IMX,KMAX),GN(IMX,KMAX),
     *     GS(IMX,KMAX),GW(IMX,KMAX),TRIGS(IMXT)
C*
      COMMON /FFTCMN/ TRIGS,IFAX
      COMMON /WKAREA/ FN,FS,GN,GS,GW
C*
      INTEGER J,I,K
C*
      IF (MNWVD .EQ. MNWV2) THEN
      ISCVC=1
      ELSEIF (MNWVD .EQ. MNWV3) THEN
      ISCVC=2
      ELSE
      STOP "ERROR (FROM RECTRG): WRONG MNWVD"
      ENDIF
C*
      DO J=1,JMAXHF
C*
      CALL RESET(FN,IMX*KDIM)
      CALL RESET(FS,IMX*KDIM)
C*
      IF (ISCVC .EQ. 1) THEN
      CALL SUMPLS(QF,FN,FS,KDIM,J)
      ELSE
      CALL SUMPLV(QF,FN,FS,KDIM,J)
      ENDIF
C*
      CALL FFT991(FN,GN,TRIGS,IFAX,1,IMX,IMAX,KDIM,1)
      CALL FFT991(FS,GS,TRIGS,IFAX,1,IMX,IMAX,KDIM,1)
C*
      DO K=1,KDIM
      DO I=1,IMAX
      F(I,J,K)=FN(I,K)
      F(I,JMAX+1-J,K)=FS(I,K)
      ENDDO
      ENDDO
C*
      ENDDO
C*
      RETURN
      END
