      SUBROUTINE QWRITE(N,QGZS,QLNP,QTMP,QDIV,QROT,QQ)
!*
!*    WRITES IN SPECTRAL COEFFICIENTS GLOBAL MODEL INITIAL CONDITION
!*
!*    ARGUMENT(DIMENSIONS)          DESCRIPTION
!*
!*    N                      INPUT: FORTRAN UNIT NUMBER FOR THE
!*                                  INITIAL CONDITION FILE
!*    GZ   (MNWV2)           INPUT: MODEL TERRAIN FIELD (SPECTRAL)
!*    QLNP (MNWV2)           INPUT: LOG OF SURFACE PRESSURE (SPECTRAL)
!*    QTMP (MNWV2,KMAX)      INPUT: TEMPERATURE (SPECTRAL)
!*    QDIV (MNWV2,KMAX)      INPUT: DIVERGENCE (SPECTRAL)
!*    QROT (MNWV2,KMAX)      INPUT: VORTICITY (SPECTRAL)
!*    QQ   (MNWV2,KQMAX      INPUT: SPECIFIC HUMIDITY (SPECTRAL)
!*
      include "decanl.h"
!*
      INTEGER MEND1,MEND2,MNWV2
      PARAMETER(MEND1=MEND+1,MEND2=MEND+2,MNWV2=MEND1*MEND2)
!*
      INTEGER N
      REAL QGZS(MNWV2),QLNP(MNWV2),QTMP(MNWV2,KMAX),
     *     QDIV(MNWV2,KMAX),QROT(MNWV2,KMAX),QQ(MNWV2,KMAX)
!*
      INTEGER K,MN
      INTEGER*4 IFDAY,IDATE(4),IDATEC(4)
      REAL*4 TOD,FHOUR,SI(KMAX+1),SL(KMAX),QWK(MNWV2)
!*
      COMMON /INDATA/ IFDAY,TOD,IDATE,IDATEC,SI,SL
!*
      CALL TRANSS(QGZS,   1,-1)
      CALL TRANSS(QLNP,   1,-1)
      CALL TRANSS(QTMP,KMAX,-1)
      CALL TRANSS(QDIV,KMAX,-1)
      CALL TRANSS(QROT,KMAX,-1)
      CALL TRANSS(QQ  ,KMAX,-1)
!*
      WRITE(N)IFDAY,TOD,IDATE,IDATEC,SI,SL
!*
      DO MN=1,MNWV2
      QWK(MN)=QGZS(MN)
      ENDDO
      WRITE(N)QWK
!*
      DO MN=1,MNWV2
      QWK(MN)=QLNP(MN)
      ENDDO
      WRITE(N)QWK
!*
      DO K=1,KMAX
      DO MN=1,MNWV2
      QWK(MN)=QTMP(MN,K)
      ENDDO
      WRITE(N)QWK
      ENDDO
!*
      DO K=1,KMAX
      DO MN=1,MNWV2
      QWK(MN)=QDIV(MN,K)
      ENDDO
      WRITE(N)QWK
      DO MN=1,MNWV2
      QWK(MN)=QROT(MN,K)
      ENDDO
      WRITE(N)QWK
      ENDDO
!*
      DO K=1,KMAX
      DO MN=1,MNWV2
      QWK(MN)=QQ(MN,K)
      ENDDO
      WRITE(N)QWK
      ENDDO
!*
      RETURN
      END
