      SUBROUTINE DECTRG(F,QF,KDIM)
!*
      include "decanl.h"
!*
      INTEGER IMX,IMXT,JMAXHF
      PARAMETER (IMX=IMAX+2,IMXT=IMAX*3/2+1,JMAXHF=JMAX/2)
      INTEGER MEND1,MEND2,MNWV2,MNWV3,MNWV1
      PARAMETER (MEND1=MEND+1,MEND2=MEND1+1,MNWV2=MEND1*MEND2,
     *           MNWV3=MNWV2+2*MEND1)
!*
      INTEGER KDIM
      REAL F(IMAX,JMAX,KDIM),QF(MNWV2,KDIM)
!*
      INTEGER J,I,K
      INTEGER IFAX(13)
      REAL FN(IMX,KMAX),FS(IMX,KMAX),GN(IMX,KMAX),
     *     GS(IMX,KMAX),TRIGS(IMXT)
!*
      COMMON /FFTCMN/ TRIGS,IFAX
!*
      CALL RESET(QF,MNWV2*KDIM)
!*
      DO J=1,JMAXHF
!*
      DO K=1,KDIM
      DO I=1,IMAX
      FN(I,K)=F(I,J,K)
      FS(I,K)=F(I,JMAX+1-J,K)
      ENDDO
      DO I=IMAX+1,IMX
      FN(I,K)=0.0
      FS(I,K)=0.0
      ENDDO
      ENDDO
!*
      CALL FFT991(FN,GN,TRIGS,IFAX,1,IMX,IMAX,KDIM,-1)
      CALL FFT991(FS,GS,TRIGS,IFAX,1,IMX,IMAX,KDIM,-1)
!*
      CALL SYMASY(FN,FS,GN,KDIM)
      CALL FL22S(FN,FS,QF,KDIM,J)
!*
      ENDDO
!*
      RETURN
      END

