#! /bin/bash -x
#            0          1          2         3           4          5          6          7           8          9	   10        11           12         13        14
idatei=( 2008122200 )
itr=0
while [ ${itr} -lt 1 ];do
nProc=`printf "PNT%4.4d  \n" ${itr}`

./runensmed.bash run 126 28 ${idatei[$itr]} 15 7 NMC >& lixo1

let itr=${itr}+1
done

exit


