      SUBROUTINE FFTRIG(TRIGS,N,MODE)
C
      INTEGER N,MODE
      REAL TRIGS(*)
C
      INTEGER IMODE,NN,L,I,NH,LA
      REAL PI,DEL,ANGLE,ONE,HALF,TWO
      DATA HALF/0.5/,ONE/1.0/,TWO/2.0/
C
      PI=TWO*ASIN(ONE)
      IMODE=IABS(MODE)
      NN=N
      IF(IMODE.GT.1.AND.IMODE.LT.6) NN=N/2
      DEL=(PI+PI)/FLOAT(NN)
      L=NN+NN
      DO 10 I=1,L,2
      ANGLE=HALF*FLOAT(I-1)*DEL
      TRIGS(I  )=COS(ANGLE)
      TRIGS(I+1)=SIN(ANGLE)
   10 CONTINUE
      IF(IMODE.EQ.1) RETURN
      IF(IMODE.EQ.8) RETURN
C
      DEL=HALF*DEL
      NH=(NN+1)/2
      L=NH+NH
      LA=NN+NN
      DO 20 I=1,L,2
      ANGLE=HALF*FLOAT(I-1)*DEL
      TRIGS(LA+I  )=COS(ANGLE)
      TRIGS(LA+I+1)=SIN(ANGLE)
   20 CONTINUE
      IF(IMODE.LE.3) RETURN
C
      DEL=HALF*DEL
      LA=LA+NN
      IF(MODE.EQ.5) GO TO 40
      DO 30 I=2,NN
      ANGLE=FLOAT(I-1)*DEL
      TRIGS(LA+I)=TWO*SIN(ANGLE)
   30 CONTINUE
      RETURN
C
   40 CONTINUE
      DEL=HALF*DEL
      DO 50 I=2,N
      ANGLE=FLOAT(I-1)*DEL
      TRIGS(LA+I)=SIN(ANGLE)
   50 CONTINUE
C
      RETURN
      END
