      SUBROUTINE LA0LA1(LA0,LA1,MEND1,NEND1,JEND1,NEND2,JEND2,MNWV2)
C*
C*    CALCULATES
C*
C*    LA0,LA1: ARRAYS THAT CONVERT (M,N) INTO DIAGONALWISE NUMBERING.
C*
      INTEGER MEND1,NEND1,JEND1,NEND2,JEND2,MNWV2
C*
      INTEGER L,NN,MMAX,MM
C*
      INTEGER LA0(MEND1,NEND1),LA1(MEND1,NEND2)
C*
      L=0
      DO 10 NN=1,NEND1
C*
      IF (NN .LE. JEND1-MEND1+1) THEN
      MMAX=MEND1
      ELSE
      MMAX=JEND1+1-NN
      ENDIF
C*
      DO 10 MM=1,MMAX
      L=L+1
      LA0(MM,NN)=L
   10 CONTINUE
C*
      L=0
      DO 20 NN=1,NEND2
C*
      IF (NN .LE. JEND2-MEND1+1) THEN
      MMAX=MEND1
      ELSE
      MMAX=JEND2-NN+1
      ENDIF
C*
      DO 20 MM=1,MMAX
      L=L+1
      LA1(MM,NN)=L
C*
   20 CONTINUE
C*
      RETURN
      END
