      SUBROUTINE STOGRD(FIN,FOUT,INC,JUMP,IMAX,LOT,IFAX,TRIGS,WORK)
C*
C*    GENERAL SPECTRAL TO GRID TRANSFORM
C*
      INTEGER INC,JUMP,IMAX,LOT,IFAX(*)
      REAL FIN(JUMP,*),FOUT(IMAX,*),TRIGS(*),WORK(*)
C*
      INTEGER KD,K,I,ISIGN
      REAL ZERO
      DATA ZERO/0.0/
C*
      KD=JUMP*LOT
      DO 10 K=1,KD
      WORK(K)=ZERO
   10 CONTINUE
C*
      ISIGN=1
      CALL FFT991(FIN,WORK,TRIGS,IFAX,INC,JUMP,IMAX,LOT,ISIGN)
C*
      DO 20 K=1,LOT
      DO 20 I=1,IMAX
      FOUT(I,K)=FIN(I,K)
   20 CONTINUE
C*
      RETURN
      END
