#!/bin/bash
#help#
#*********************************************************************************#
#                                                                                 #
# script to run CPTEC Global Model on PC Clusters under MPI Scali                 #
# and Sun Grid Engine without OpenMP                                              #
#                                                                                 #
# assumptions: assume present at the same directory:                              #
#              ParModel_MPI (Global Model Executable file)                        #
#              MODELIN (Global Model input Namelist file)                         #
#                                                                                 #
# usage: run_multi_UNA cpu_mpi cpu_node name TRC LV LABELI LABELF hold            #
# where:                                                                          #
# cpu_mpi: integer, the desired number of mpi processes                           #
# cpu_node: integer, the desired number of mpi processes per shared memory node   #
# name: character, the job name (for SGE)                                         #
# hold: any, present or not;                                                      #
#            if absent, script finishes after queueing job;                       #
#            if present, script holds till job completion                         #
#*********************************************************************************#
#help#
#
#       Help:
#
set -x
if [ "${1}" = "help" -o -z "${1}" ]
then
  cat < ${0} | sed -n '/^#help#/,/^#help#/p'
  exit 1
fi

export CASE=$4
if [ ${#CASE} -ne 10 ]; then
  cat < ${0} | sed -n '/^#help#/,/^#help#/p'
  exit 1
else
#
# SETTING THE APPROPRIATED ENVIRONMENT
#
  PATHA=`pwd`
  export FILEENV=`find ${PATHA} -maxdepth 2 -name EnvironmentalVariablesOENS -print`
  export PATHENV=`dirname ${FILEENV}`
fi
if [ ${#5} -ne 10 ]; then
  echo "LABELI is not set" 
  exit 3
else
  export LABELI=${5}  
fi

if [ -z "${6}" ]; then
  echo "Directory is not set" 
  exit 3
else
  export VERDIR=${6}  
fi

if [ -z "${7}" ]; then
  echo "Total Area for Directory verification is not set" 
  exit 3
else
  export PREFIX=${7}  
fi

if [ -z "${8}" ]; then
  echo "Total Area for Directory verification is not set" 
  exit 3
else
  export SIZEDIR=${8}  
fi

. ${FILEENV} ${CASE} ${PREFIX}

s=$(find $VERDIR -name "*${PREFIX}*" -ls |awk 'BEGIN { s=c=0 } { s+=$7;c+=1 } END { printf( "%17d",s)}')
echo "TAMANHO TOTAL: $s"

if [ $s -ge $SIZEDIR ]; then
   echo "Files Ok - $LABELI"
   smslabel Info "Files Ok for ${LABELI}"
else
   echo "ERROR IN FILE VERIFICATION"
   smslabel Info "ERROR: Number of files incorrect" "${LABELI}"
   exit 4
fi

exit 0
