#! /bin/bash

#help#
#-------------------------------------------------------------------------------------------------#
#                               Brazilian global Atmospheric Model                                #
#-------------------------------------------------------------------------------------------------#
# Descrição:                                                                                      #
#     Script para ajustar as variáveis de ambiente do BAM                                         #
#                                                                                                 #
# Uso:                                                                                            #
#     ./EnvironmentalVariablesMCGA RESOL PREFIX                                                   #
#                                                                                                 #
# Exemplo:                                                                                        #
#     ./EnvironmentalVariablesMCGA TQ00126L028 NMC                                                #
#                                                                                                 #
# Opções:                                                                                         #
#     * RESOL.: resolução completa do modelo no formato TQXXXXLXXX                                #  
#               (eg., TQ0062L028, TQ00126L028, TQ00213L042, etc)                                  #
#     * PREFIX: prefixo da análise (eg., NMC, CPT, AVN)                                           #
#                                                                                                 #
# Notas:                                                                                          #
#     Este script auxiliar é chamado pelos scripts principais do modelo                           #
#                                                                                                 #
# DMD/CPTEC/INPE, 2021                                                                            #
#-------------------------------------------------------------------------------------------------#
#help#

#
# Função para imprimir o cabeçalho do script
#

function usageprincipal()
{
  cat < ${0} | sed '1,/^#help#/d;/^#help#/,$d'
}

if [ -z "${1}" ]
then
  echo "TRCLV is not set"  
else
  export TRCLV=${1}
fi

if [ -z "${2}" ]
then
  echo "PREFIX is not set"  
else
  export PREFIX=${2}
fi

#
# Caminhos
#

# Caminho do BAM no HOME
export PATHBASE=/mnt/beegfs/carlos.bastarz/oensMB09

# Caminho do BAM no scratchin (SUBMIT_HOME)
export DK=/mnt/beegfs/carlos.bastarz/oensMB09

# Caminho do BAM no scratchout (SUBMIT_WORK)
export DK2=/mnt/beegfs/carlos.bastarz/oensMB09

export HOME_suite=${PATHBASE} ; mkdir -p ${HOME_suite}
export DK_suite=${DK}         ; mkdir -p ${DK_suite}
export DK_suite2=${DK2}       ; mkdir -p ${DK_suite2}

export tmstp=$(date +'%s')

#
# Variáveis do PBS
#

export HSTMAQ=$(uname -n)
export MAQUI=$(uname -s)
export QUOTA=CPTEC
export pbs_server2=headnode
export pbs_server1=headnode
export QSUB=/usr/bin/sbatch
export QUEUE=batch
export QUEUEM=batch
export QUEUEP=batch
export AUX_QUEUE=batch
export WALLTIME="04:00:00"
export WALLTIME6="00:30:00"
export AUX_WALLTIME="00:30:00"

export PREFXI="${PREFIX}"     # preffix for name of input files
export PREFXO="${PREFIX}"     # preffix for name of output files

#
# Escolha do tipo de análise
#
# Se a análise for espectral (eg., gdas1.THHZ.SAnl.YYYYMMDDHH; gblav.THHZ.SAnl.YYYYMMDDHH), até 2017071912:
# --> DataGDAS="Spec"
# --> AnlPref="gdas1" ou AnlPref="gblav"
#
# Se a análise for em ponto de grade (eg., gdas.THHZ.atmanl.nemsio.YYYYMMDDHH), a partir de 2017071912:
# --> DataGDAS="Grid"
# --> AnlPref="gdas"
#

export DataGDAS="Grid"         # Spec == Anl. Spec. NCEP; Grid == Anl. Grid NCEP 
export AnlPref="gblav"         # gdas1/gblav == Anl. Spec. NCEP; gdas/gblav == Anl. Grid. NCEP 

export GSSTEP=1

#
# Utilitários
#

export DIRGRADS=/home/carlos.bastarz/bin
export caldate=/mnt/beegfs/carlos.bastarz/BAM_V1.2.1/utils/bin/caldate.3.0.1
export inctime=/home/carlos.bastarz/bin/inctime

# Indica se o código do modelo e do método de perturbação a ser utilizado foi compilado com o Intel (true) ou GNU (false)
export USE_INTEL=false

#
# Singularity Container
#

# Indica se deve ser utilizado o container singularity para executar os códigos do modelo e do método de perturbação (true = usar)
export USE_SINGULARITY=true

export HOMEBIND=/home/carlos.bastarz
export WORKBIND=/mnt/beegfs/carlos.bastarz

# Indica o nome da imagem com o container a ser utilizado para executar os códigos do modelo e do método de perturbação (esta imagem deve conter todos os executáveis)
export SIFIMAGE=/mnt/beegfs/carlos.bastarz/containers/oensMB09_BAM_V1.2.1_Env_XC50-Ubuntu-18.04_gcc-4.8.5_mpich-3.3_v0.2.sif

# Indica o diretório de instalação do oensMB09 (onde estão alocados os executáveis do método de perturbação) dentro do container
export SIFOENSMB09BIN=/opt/oensMB09-3-testes-com-o-compilador-intel
