#!/bin/csh

echo "removendo arquivos do disco: /gfs/home0/ensglob/oens"

rm -f /gfs/home0/ensglob/oens/decanl/datain/GANL*
rm -f /gfs/home0/ensglob/oens/decanl/datain/GEOF*

rm -f /gfs/home0/ensglob/oens/eof/datain/templ*

rm -f /gfs/home0/ensglob/oens/pre/dataout/T126/snwgrd*
rm -f /gfs/home0/ensglob/oens/pre/dataout/T126/sstgwk*

rm -f /gfs/home0/ensglob/oens/recanl/datain/GANL*
rm -f /gfs/home0/ensglob/oens/recanl/datain/GPER*
rm -f /gfs/home0/ensglob/oens/recanl/datain/GFCT*

rm -f /gfs/home0/ensglob/oens/recfct/datain/GFCT*


echo "removendo arquivos do disco: /gfs/dk02/ensglob/oens"

rm -f /gfs/dk02/ensglob/oens/recfct/dataout/T126L28/GFCT*

rm -f /gfs/dk02/ensglob/oens/eof/dataout/T126L28/tem*
rm -f /gfs/dk02/ensglob/oens/eof/dataout/T126L28/win*
rm -f /gfs/dk02/ensglob/oens/eof/dataout/T126L28/hum*

rm -f /gfs/dk02/ensglob/oens/model/datain/GANL*
rm -f /gfs/dk02/ensglob/oens/model/datain/GFCT*
rm -f /gfs/dk02/ensglob/oens/model/datain/GPER*
rm -f /gfs/dk02/ensglob/oens/model/datain/lst.*
rm -f /gfs/dk02/ensglob/oens/model/datain/*R.unf.T126L28
rm -f /gfs/dk02/ensglob/oens/model/datain/snowfd*
rm -f /gfs/dk02/ensglob/oens/model/datain/sstwkl*

rm -f /gfs/dk02/ensglob/oens/model/dataout/T126L28/GDHN*
rm -f /gfs/dk02/ensglob/oens/model/dataout/T126L28/GFCT*
rm -f /gfs/dk02/ensglob/oens/model/dataout/T126L28/GFGH*
rm -f /gfs/dk02/ensglob/oens/model/dataout/T126L28/GPER*
rm -f /gfs/dk02/ensglob/oens/model/dataout/T126L28/GPRG*.fct.*
rm -f /gfs/dk02/ensglob/oens/model/dataout/T126L28/GPRG*.dir.*
rm -f /gfs/dk02/ensglob/oens/model/dataout/T126L28/GPRG*
rm -f /gfs/dk02/ensglob/oens/model/dataout/T126L28/Size*

rm -f /gfs/dk02/ensglob/oens/pos/dataout/T126L28/GPOS*.lst
rm -f /gfs/dk02/ensglob/oens/pos/dataout/T126L28/GPOS*.ctl
rm -f /gfs/dk02/ensglob/oens/pos/dataout/T126L28/*.T126L28
rm -f /gfs/dk02/ensglob/oens/pos/dataout/T126L28/Size*

rm -f /gfs/dk02/ensglob/oens/rdpert/dataout/T126L28/GANL*

rm -f /gfs/dk02/ensglob/oens/recanl/dataout/T126L28/GANL*
rm -f /gfs/dk02/ensglob/oens/recanl/dataout/T126L28/GPER*


