      SUBROUTINE GRDTOS(FIN,INC,JUMP,IMAX,LOT,IFAX,TRIGS,WORK)
C*
C*    GENERAL GRID TO SPECTRAL FAST FOURIER TRANSFORM
C*
      INTEGER INC,JUMP,IMAX,LOT,IFAX(*)
      REAL FIN(*),TRIGS(*),WORK(*)
C*
      INTEGER KD,K,ISIGN
      REAL ZERO
      DATA ZERO/0.0/
C*
      KD=JUMP*LOT
      DO 10 K=1,KD
      WORK(K)=ZERO
   10 CONTINUE
C*
      ISIGN=-1
      CALL FFT991(FIN,WORK,TRIGS,IFAX,INC,JUMP,IMAX,LOT,ISIGN)
C*
      RETURN
      END
