      SUBROUTINE REVROW(H,IMAX,JMAX)
C*
C*    FLIPS OVER THE ROWS OF A MATRIX
C*
C*    INPUT:
C*    H(IMAX,JMAX) - MATRIX TO BE FLIPPED
C*    IMAX         - COLUMN DIMENSION OF H(IMAX,JMAX)
C*    JMAX         - ROW DIMENSION OF H(IMAX,JMAX)
C*
C*    OUTPUT:
C*    H(IMAX,JMAX) - FLIPPED MATRIX
C*
      INTEGER IMAX,JMAX
      REAL H(IMAX,JMAX)
C*
      INTEGER JMAXD,J1,J2,I
      REAL HT
C*
      JMAXD=JMAX/2
      DO J1=1,JMAXD
      J2=JMAX+1-J1
      DO I=1,IMAX
      HT=H(I,J1)
      H(I,J1)=H(I,J2)
      H(I,J2)=HT
      ENDDO
      ENDDO
C*
      RETURN
      END
