      SUBROUTINE SMTCFT(CFT,RED,MEND1,NEND1,JEND1,MNWV2)
C*
C*    SMOOTHES SPHERICAL HARMONICS COEFFICIENTS
C*                       USING HOSKIN'S(?) FILTER
C*
C*    INPUT:
C*    CFT(MNWV2) - SPHERICAL HARMONICS COEFFICIENTS
C*    RED        - COEFFICIENT FOR FILTERING (=10.0)
C*    MEND1,NEND1,JEND1,MNWV2 - TRUNCATION
C*
C*    OUTPUT:
C*    CFT(MNWV2) - SMOOTHED SPHERICAL HARMONICS COEFFICIENTS
C*
      INTEGER MEND1,NEND1,JEND1,MNWV2
      REAL RED
      REAL CFT(MNWV2)
C*
      INTEGER MNJ,MND,MN,NN,MM,MMAX,MNS
      REAL RM,CX,RMN,CK
C*
C*    DEFINING CONSTANTS
C*
      MNJ=JEND1-MEND1+1
      MND=MEND1+NEND1-1
      RM=FLOAT(MND-1)*FLOAT(MND)
      CX=-LOG(RED)/(RM*RM)
C*
C*    BEGIN SMOOTHING
C*
      MN=0
      DO NN=1,NEND1
C*
C*    CHOOSING THE TRUNCATION
C*
      IF (NN .LE. MNJ) THEN
      MMAX=MEND1
      ELSE
      MMAX=JEND1-NN+1
      ENDIF
C*
      DO MM=1,MMAX
      MN=MN+1
C*
C*    PERFORMING SMOOTHING
C*
      MNS=MM+NN-1
      RMN=FLOAT(MNS-1)*FLOAT(MNS)
      CK=EXP(CX*RMN*RMN)
      CFT(2*MN-1)=CFT(2*MN-1)*CK
      CFT(2*MN  )=CFT(2*MN  )*CK
C*
      ENDDO
C*
      ENDDO
C*
      RETURN
      END
