SUBROUTINE SUBDOMAIN(IMAX,JMAX,INARRAY,SDIBEG,SDIEND,SDJBEG,SDJEND,OUTARRAY,NXY)
   INTEGER, INTENT(IN) :: IMAX
   INTEGER, INTENT(IN) :: JMAX
   REAL, INTENT(IN),DIMENSION(IMAX,JMAX) :: INARRAY
   INTEGER, INTENT(IN) :: SDIBEG ! BEGINNING I INDEX (1,2,...,etc) OF THE REQUIRED SUBDOMAIN
   INTEGER, INTENT(IN) :: SDIEND ! ENDING I INDEX (1,2,...,etc) OF THE REQUIRED SUBDOMAIN
   INTEGER, INTENT(IN) :: SDJBEG ! BEGINNING J INDEX (1,2,...,etc) OF THE REQUIRED SUBDOMAIN
   INTEGER, INTENT(IN) :: SDJEND ! ENDING J INDEX (1,2,...,etc) OF THE REQUIRED SUBDOMAIN
   LOGICAL :: MASK(IMAX,JMAX)
   REAL, INTENT(OUT), DIMENSION ((SDIEND-SDIBEG+1)*(SDJEND-SDJBEG+1)) :: OUTARRAY
   INTEGER, INTENT(OUT) :: NXY
   INTEGER :: NX,NY

   ! ----
   !     SET UP A MASK 
   !     OUTSIDE THE LIMITS DEFINED THE MASK IS .FALSE., INSIDE IS .TRUE.
   ! ----
   MASK=.FALSE.
   DO NY = SDJBEG,SDJEND 
   DO NX = SDIBEG,SDIEND 
      MASK(NX,NY)=.TRUE.
   ENDDO
   ENDDO 

   NXY = 0 
   DO J=1,JMAX
   DO I=1,IMAX
      IF(MASK(I,J))THEN
         NXY = NXY + 1
         OUTARRAY(NXY)=INARRAY(I,J)
      ENDIF
   ENDDO
   ENDDO

END SUBROUTINE SUBDOMAIN
